/* Automatically generated by Amaranth 0.3. Do not edit. */
/* Generated by Yosys 0.13+3 (git sha1 61324cf55, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "top.tb.dut.delayer" *)
(* generator = "Amaranth" *)
module delayer(sync_1e6_clk, start, done, counter_out, sync_1e6_rst);
  reg \$auto$verilog_backend.cc:2083:dump_module$50  = 0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:21" *)
  wire \$1 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *)
  wire [32:0] \$10 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *)
  wire [32:0] \$11 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
  wire \$13 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:45" *)
  wire [32:0] \$15 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:45" *)
  wire [32:0] \$16 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$18 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$20 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *)
  wire \$22 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
  wire \$24 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$3 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$5 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *)
  wire [32:0] \$7 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *)
  wire [32:0] \$8 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  output [31:0] counter_out;
  reg [31:0] counter_out = 32'd0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  reg [31:0] \counter_out$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:13" *)
  output done;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
  reg [1:0] fsm_state = 2'h1;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:10" *)
  wire [31:0] reload;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  input start;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  input sync_1e6_clk;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  input sync_1e6_rst;
  assign \$11  = counter_out - (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *) 1'h1;
  assign \$18  = counter_out > (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) 1'h0;
  assign \$1  = ! (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:21" *) fsm_state;
  assign \$20  = start & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) \$18 ;
  assign \$22  = counter_out == (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *) 1'h1;
  assign \$3  = counter_out > (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) 1'h0;
  assign \$5  = start & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) \$3 ;
  assign \$8  = counter_out - (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *) 1'h1;
  always @(posedge sync_1e6_clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge sync_1e6_clk)
    counter_out <= \counter_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \counter_out$next  = counter_out;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/1" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:23" */
      2'h1:
        begin
          \counter_out$next  = 32'd1000000;
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
          casez (\$5 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" */
            1'h1:
                \counter_out$next  = \$8 [31:0];
          endcase
        end
      /* \amaranth.decoding  = "RUNNING/2" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:36" */
      2'h2:
          \counter_out$next  = \$11 [31:0];
      /* \amaranth.decoding  = "DONE/0" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:41" */
      2'h0:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
          casez (\$13 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" */
            1'h1:
                \counter_out$next  = \$16 [31:0];
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \counter_out$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$50 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/1" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:23" */
      2'h1:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
          casez (\$20 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" */
            1'h1:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "RUNNING/2" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:36" */
      2'h2:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *)
          casez (\$22 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
      /* \amaranth.decoding  = "DONE/0" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:41" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
          casez (\$24 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" */
            1'h1:
                \fsm_state$next  = 2'h2;
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:48" */
            default:
                \fsm_state$next  = 2'h1;
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \fsm_state$next  = 2'h1;
    endcase
  end
  assign \$7  = \$8 ;
  assign \$10  = \$11 ;
  assign \$15  = \$16 ;
  assign reload = 32'd0;
  assign done = \$1 ;
  assign \$13  = 1'h0;
  assign \$16  = 33'h1ffffffff;
  assign \$24  = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.tb.dut" *)
(* generator = "Amaranth" *)
module dut(sync_1e6_clk, ui__trigger, ui__done, debug__count, sync_1e6_rst);
  reg \$auto$verilog_backend.cc:2083:dump_module$51  = 0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:40" *)
  output [31:0] debug__count;
  reg [31:0] debug__count = 32'd0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:46" *)
  reg [31:0] \debug__count$3  = 32'd0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:46" *)
  reg [31:0] \debug__count$3$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:40" *)
  reg [31:0] \debug__count$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  wire [31:0] delayer_counter_out;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:13" *)
  wire delayer_done;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  reg delayer_start = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  reg \delayer_start$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  input sync_1e6_clk;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  input sync_1e6_rst;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:39" *)
  output ui__done;
  reg ui__done = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:45" *)
  reg \ui__done$2  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:45" *)
  reg \ui__done$2$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:39" *)
  reg \ui__done$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:39" *)
  input ui__trigger;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:45" *)
  reg \ui__trigger$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:45" *)
  reg \ui__trigger$1$next ;
  always @(posedge sync_1e6_clk)
    \debug__count$3  <= \debug__count$3$next ;
  always @(posedge sync_1e6_clk)
    \ui__done$2  <= \ui__done$2$next ;
  always @(posedge sync_1e6_clk)
    delayer_start <= \delayer_start$next ;
  always @(posedge sync_1e6_clk)
    debug__count <= \debug__count$next ;
  always @(posedge sync_1e6_clk)
    ui__done <= \ui__done$next ;
  always @(posedge sync_1e6_clk)
    \ui__trigger$1  <= \ui__trigger$1$next ;
  delayer delayer (
    .counter_out(delayer_counter_out),
    .done(delayer_done),
    .start(delayer_start),
    .sync_1e6_clk(sync_1e6_clk),
    .sync_1e6_rst(sync_1e6_rst)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__trigger$1$next  = ui__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__trigger$1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__done$next  = \ui__done$2 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \debug__count$next  = \debug__count$3 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \debug__count$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \delayer_start$next  = \ui__trigger$1 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \delayer_start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \ui__done$2$next  = delayer_done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$2$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$51 ) begin end
    \debug__count$3$next  = delayer_counter_out;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \debug__count$3$next  = 32'd0;
    endcase
  end
endmodule

(* \amaranth.hierarchy  = "top.i_button_ffsync" *)
(* generator = "Amaranth" *)
module i_button_ffsync(i_unsync_buttons__fireA, i_unsync_buttons__fireB, i_unsync_buttons__up, i_unsync_buttons__down, i_unsync_buttons__left, i_unsync_buttons__right, i_buttons__pwr, i_buttons__left, i_buttons__right, rst, clk, i_unsync_buttons__pwr);
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  input clk;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_buttons__down;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_buttons__fireA;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_buttons__fireB;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  output i_buttons__left;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  output i_buttons__pwr;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  output i_buttons__right;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_buttons__up;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__down;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__fireA;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__fireB;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__left;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__pwr;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__right;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  input i_unsync_buttons__up;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  input rst;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  reg [6:0] stage0 = 7'h00;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  wire [6:0] \stage0$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  reg [6:0] stage1 = 7'h00;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  wire [6:0] \stage1$next ;
  always @(posedge clk)
    stage1 <= stage0;
  always @(posedge clk)
    stage0 <= { i_unsync_buttons__right, i_unsync_buttons__left, i_unsync_buttons__down, i_unsync_buttons__up, i_unsync_buttons__fireB, i_unsync_buttons__fireA, i_unsync_buttons__pwr };
  assign { i_buttons__right, i_buttons__left, i_buttons__down, i_buttons__up, i_buttons__fireB, i_buttons__fireA, i_buttons__pwr } = stage1;
  assign \stage1$next  = stage0;
  assign \stage0$next  = { i_unsync_buttons__right, i_unsync_buttons__left, i_unsync_buttons__down, i_unsync_buttons__up, i_unsync_buttons__fireB, i_unsync_buttons__fireA, i_unsync_buttons__pwr };
endmodule

(* \amaranth.hierarchy  = "top.pin_button_down_0" *)
(* generator = "Amaranth" *)
module pin_button_down_0(button_down_0__io, button_down_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  IB button_down_0_0 (
    .I(button_down_0__io),
    .O(button_down_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_0" *)
(* generator = "Amaranth" *)
module pin_button_fire_0(button_fire_0__io, button_fire_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  IB button_fire_0_0 (
    .I(button_fire_0__io),
    .O(button_fire_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_1" *)
(* generator = "Amaranth" *)
module pin_button_fire_1(button_fire_1__io, button_fire_1__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  IB button_fire_1_0 (
    .I(button_fire_1__io),
    .O(button_fire_1__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_left_0" *)
(* generator = "Amaranth" *)
module pin_button_left_0(button_left_0__io, button_left_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  IB button_left_0_0 (
    .I(button_left_0__io),
    .O(button_left_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_pwr_0" *)
(* generator = "Amaranth" *)
module pin_button_pwr_0(button_pwr_0__io, button_pwr_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire button_pwr_0__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) button_pwr_0__i_n;
  IB button_pwr_0_0 (
    .I(button_pwr_0__io),
    .O(button_pwr_0__i_n)
  );
  assign button_pwr_0__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_button_right_0" *)
(* generator = "Amaranth" *)
module pin_button_right_0(button_right_0__io, button_right_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  IB button_right_0_0 (
    .I(button_right_0__io),
    .O(button_right_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_up_0" *)
(* generator = "Amaranth" *)
module pin_button_up_0(button_up_0__io, button_up_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  IB button_up_0_0 (
    .I(button_up_0__io),
    .O(button_up_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_clk25_0" *)
(* generator = "Amaranth" *)
module pin_clk25_0(clk25_0__io, clk25_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  IB clk25_0_0 (
    .I(clk25_0__io),
    .O(clk25_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__en" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__en(esp32_spi_0__en__io, esp32_spi_0__en__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__en__o;
  OB esp32_spi_0__en_0 (
    .I(esp32_spi_0__en__o),
    .O(esp32_spi_0__en__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio0" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio0(esp32_spi_0__gpio0__io, esp32_spi_0__gpio0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:531" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__gpio0__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__oe;
  BB esp32_spi_0__gpio0_0 (
    .B(esp32_spi_0__gpio0__io),
    .I(esp32_spi_0__gpio0__o),
    .O(esp32_spi_0__gpio0__i),
    .T(1'h1)
  );
  assign esp32_spi_0__gpio0__oe = 1'h0;
  assign \$1  = 1'h1;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio12_cipo" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio12_cipo(esp32_spi_0__gpio12_cipo__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio12_cipo__o;
  OB esp32_spi_0__gpio12_cipo_0 (
    .I(1'h0),
    .O(esp32_spi_0__gpio12_cipo__io)
  );
  assign esp32_spi_0__gpio12_cipo__o = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio16_sclk" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio16_sclk(esp32_spi_0__gpio16_sclk__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio16_sclk__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  IB esp32_spi_0__gpio16_sclk_0 (
    .I(esp32_spi_0__gpio16_sclk__io),
    .O(esp32_spi_0__gpio16_sclk__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio4_copi" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio4_copi(esp32_spi_0__gpio4_copi__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio4_copi__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  IB esp32_spi_0__gpio4_copi_0 (
    .I(esp32_spi_0__gpio4_copi__io),
    .O(esp32_spi_0__gpio4_copi__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio5_cs" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio5_cs(esp32_spi_0__gpio5_cs__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio5_cs__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire esp32_spi_0__gpio5_cs__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) esp32_spi_0__gpio5_cs__i_n;
  IB esp32_spi_0__gpio5_cs_0 (
    .I(esp32_spi_0__gpio5_cs__io),
    .O(esp32_spi_0__gpio5_cs__i_n)
  );
  assign esp32_spi_0__gpio5_cs__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__rx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__rx(esp32_spi_0__rx__io, esp32_spi_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  IB esp32_spi_0__rx_0 (
    .I(esp32_spi_0__rx__io),
    .O(esp32_spi_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__tx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__tx(esp32_spi_0__tx__io, esp32_spi_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__tx__o;
  OB esp32_spi_0__tx_0 (
    .I(esp32_spi_0__tx__o),
    .O(esp32_spi_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_0" *)
(* generator = "Amaranth" *)
module pin_led_0(led_0__io, led_0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_0__o;
  OB led_0_0 (
    .I(led_0__o),
    .O(led_0__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_1" *)
(* generator = "Amaranth" *)
module pin_led_1(led_1__io, led_1__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_1__o;
  OB led_1_0 (
    .I(led_1__o),
    .O(led_1__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_2" *)
(* generator = "Amaranth" *)
module pin_led_2(led_2__io, led_2__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_2__o;
  OB led_2_0 (
    .I(led_2__o),
    .O(led_2__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_3" *)
(* generator = "Amaranth" *)
module pin_led_3(led_3__io, led_3__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_3__o;
  OB led_3_0 (
    .I(led_3__o),
    .O(led_3__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_4" *)
(* generator = "Amaranth" *)
module pin_led_4(led_4__io, led_4__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_4__o;
  OB led_4_0 (
    .I(led_4__o),
    .O(led_4__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_5" *)
(* generator = "Amaranth" *)
module pin_led_5(led_5__io, led_5__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_5__o;
  OB led_5_0 (
    .I(led_5__o),
    .O(led_5__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_6" *)
(* generator = "Amaranth" *)
module pin_led_6(led_6__io, led_6__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_6__o;
  OB led_6_0 (
    .I(led_6__o),
    .O(led_6__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_7" *)
(* generator = "Amaranth" *)
module pin_led_7(led_7__io, led_7__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_7__o;
  OB led_7_0 (
    .I(led_7__o),
    .O(led_7__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__dtr" *)
(* generator = "Amaranth" *)
module pin_uart_0__dtr(uart_0__dtr__io, uart_0__dtr__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  IB uart_0__dtr_0 (
    .I(uart_0__dtr__io),
    .O(uart_0__dtr__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rts" *)
(* generator = "Amaranth" *)
module pin_uart_0__rts(uart_0__rts__io, uart_0__rts__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  IB uart_0__rts_0 (
    .I(uart_0__rts__io),
    .O(uart_0__rts__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rx" *)
(* generator = "Amaranth" *)
module pin_uart_0__rx(uart_0__rx__io, uart_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  IB uart_0__rx_0 (
    .I(uart_0__rx__io),
    .O(uart_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__tx" *)
(* generator = "Amaranth" *)
module pin_uart_0__tx(uart_0__tx__io, uart_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input uart_0__tx__o;
  OB uart_0__tx_0 (
    .I(uart_0__tx__o),
    .O(uart_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.tb" *)
(* generator = "Amaranth" *)
module tb(ui__done, ui__reset, leds, sync_1e6_rst, rst, sync_1e6_clk, clk, clk25_0__i, ui__trigger);
  reg \$auto$verilog_backend.cc:2083:dump_module$52  = 0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:120" *)
  wire \$11 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:120" *)
  wire \$13 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:120" *)
  wire \$14 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *)
  wire [4:0] \$4 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *)
  wire [4:0] \$5 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *)
  wire [4:0] \$7 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *)
  wire \$8 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  output clk;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input clk25_0__i;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:116" *)
  reg [3:0] clk_counter = 4'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:116" *)
  reg [3:0] \clk_counter$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:90" *)
  reg [31:0] debug__count = 32'd0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:90" *)
  reg [31:0] \debug__count$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:40" *)
  wire [31:0] dut_debug__count;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:39" *)
  wire dut_ui__done;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:39" *)
  reg dut_ui__trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:39" *)
  reg \dut_ui__trigger$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:82" *)
  output [7:0] leds;
  reg [7:0] leds = 8'h00;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:82" *)
  wire [7:0] \leds$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  output rst;
  reg rst = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  reg \rst$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  output sync_1e6_clk;
  reg sync_1e6_clk = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  reg \sync_1e6_clk$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  output sync_1e6_rst;
  reg sync_1e6_rst = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  reg \sync_1e6_rst$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  output ui__done;
  reg ui__done = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:89" *)
  reg \ui__done$2  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:89" *)
  reg \ui__done$2$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  reg \ui__done$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  input ui__reset;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:89" *)
  reg \ui__reset$3  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:89" *)
  reg \ui__reset$3$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  input ui__trigger;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:89" *)
  reg \ui__trigger$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:89" *)
  reg \ui__trigger$1$next ;
  assign \$7  = \$8  ? (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *) 5'h00 : \$5 ;
  assign \$11  = ~ (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:120" *) sync_1e6_clk;
  assign \$14  = ! (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:120" *) clk_counter;
  assign \$13  = \$14  ? (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:120" *) \$11  : sync_1e6_clk;
  assign \$5  = clk_counter + (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *) 1'h1;
  assign \$8  = clk_counter == (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:118" *) 4'hb;
  always @(posedge clk)
    sync_1e6_clk <= \sync_1e6_clk$next ;
  always @(posedge clk)
    sync_1e6_rst <= \sync_1e6_rst$next ;
  always @(posedge clk)
    clk_counter <= \clk_counter$next ;
  always @(posedge clk)
    rst <= \rst$next ;
  always @(posedge sync_1e6_clk)
    leds <= debug__count[17:10];
  always @(posedge sync_1e6_clk)
    debug__count <= \debug__count$next ;
  always @(posedge sync_1e6_clk)
    \ui__done$2  <= \ui__done$2$next ;
  always @(posedge sync_1e6_clk)
    dut_ui__trigger <= \dut_ui__trigger$next ;
  always @(posedge sync_1e6_clk)
    \ui__reset$3  <= \ui__reset$3$next ;
  always @(posedge sync_1e6_clk)
    ui__done <= \ui__done$next ;
  always @(posedge sync_1e6_clk)
    \ui__trigger$1  <= \ui__trigger$1$next ;
  dut dut (
    .debug__count(dut_debug__count),
    .sync_1e6_clk(sync_1e6_clk),
    .sync_1e6_rst(sync_1e6_rst),
    .ui__done(dut_ui__done),
    .ui__trigger(dut_ui__trigger)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__trigger$1$next  = ui__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__trigger$1$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__done$next  = \ui__done$2 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \sync_1e6_rst$next  = \ui__reset$3 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_1e6_rst$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \sync_1e6_clk$next  = \$13 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_1e6_clk$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__reset$3$next  = ui__reset;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__reset$3$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \dut_ui__trigger$next  = \ui__trigger$1 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \dut_ui__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \ui__done$2$next  = dut_ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$2$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \debug__count$next  = dut_debug__count;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \debug__count$next  = 32'd0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \rst$next  = \ui__reset$3 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \rst$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$52 ) begin end
    \clk_counter$next  = \$7 [3:0];
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \clk_counter$next  = 4'h0;
    endcase
  end
  assign \$4  = \$7 ;
  assign clk = clk25_0__i;
  assign \leds$next  = debug__count[17:10];
endmodule

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(led_0__io, led_1__io, led_2__io, led_3__io, led_4__io, led_5__io, led_6__io, led_7__io, esp32_spi_0__en__io, esp32_spi_0__tx__io, esp32_spi_0__rx__io, esp32_spi_0__gpio4_copi__io, esp32_spi_0__gpio5_cs__io, esp32_spi_0__gpio12_cipo__io, esp32_spi_0__gpio16_sclk__io, uart_0__rx__io, uart_0__tx__io, uart_0__rts__io, uart_0__dtr__io, button_pwr_0__io, button_fire_0__io
, button_fire_1__io, button_up_0__io, button_down_0__io, button_left_0__io, button_right_0__io, clk25_0__io, esp32_spi_0__gpio0__io);
  reg \$auto$verilog_backend.cc:2083:dump_module$53  = 0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
  wire \$1 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:297" *)
  wire \$11 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$13 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$15 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:300" *)
  wire \$17 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$19 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$21 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:303" *)
  wire \$23 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:295" *)
  wire \$25 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:295" *)
  wire \$27 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:298" *)
  wire \$29 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
  wire \$3 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:298" *)
  wire \$31 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:301" *)
  wire \$33 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:301" *)
  wire \$35 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:304" *)
  wire \$37 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:304" *)
  wire \$39 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
  wire \$41 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
  wire \$43 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
  wire \$45 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$47 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$49 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
  wire \$5 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:297" *)
  wire \$51 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$53 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$55 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:300" *)
  wire \$57 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$59 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$61 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:303" *)
  wire \$63 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$65 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$67 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$69 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$7 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$71 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$9 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:328" *)
  reg \$sample$s$reset$sync_1e6$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:328" *)
  wire \$sample$s$reset$sync_1e6$1$next ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:325" *)
  reg \$sample$s$trigger$sync_1e6$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:325" *)
  wire \$sample$s$trigger$sync_1e6$1$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  wire clk;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_button_ffsync_i_buttons__left;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_button_ffsync_i_buttons__pwr;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:266" *)
  wire i_button_ffsync_i_buttons__right;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__down = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__down$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__fireA = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__fireA$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__fireB = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__fireB$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__left = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__left$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__pwr = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__pwr$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__right = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__right$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg i_button_ffsync_i_unsync_buttons__up = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  reg \i_button_ffsync_i_unsync_buttons__up$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_down_0_button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_fire_0_button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_fire_1_button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_left_0_button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_pwr_0_button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_right_0_button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_up_0_button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__en_esp32_spi_0__en__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__en_esp32_spi_0__en__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__tx_esp32_spi_0__tx__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_0_led_0__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_0_led_0__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_1_led_1__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_1_led_1__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_2_led_2__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_2_led_2__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_3_led_3__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_3_led_3__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_4_led_4__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_4_led_4__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_5_led_5__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_5_led_5__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_6_led_6__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_6_led_6__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_7_led_7__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_7_led_7__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__dtr_uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rts_uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rx_uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_uart_0__tx_uart_0__tx__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_uart_0__tx_uart_0__tx__o$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:328" *)
  reg reset = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:328" *)
  reg \reset$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:105" *)
  wire rst;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  wire sync_1e6_clk;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:114" *)
  wire sync_1e6_rst;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire tb_clk25_0__i;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:82" *)
  wire [7:0] tb_leds;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  wire tb_ui__done;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  reg tb_ui__reset = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  reg \tb_ui__reset$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  reg tb_ui__trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:81" *)
  reg \tb_ui__trigger$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:325" *)
  reg trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:325" *)
  reg \trigger$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:318" *)
  reg ui__done = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:318" *)
  reg \ui__done$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:318" *)
  reg ui__reset = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:318" *)
  reg \ui__reset$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:318" *)
  reg ui__trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:318" *)
  reg \ui__trigger$next ;
  assign \$9  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$11  = \$7  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:297" *) \$9 ;
  assign \$15  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$17  = \$13  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:300" *) \$15 ;
  assign \$19  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$23  = \$19  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:303" *) \$21 ;
  assign \$25  = ~ (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:295" *) i_button_ffsync_i_buttons__pwr;
  assign \$29  = ~ (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:298" *) i_button_ffsync_i_buttons__pwr;
  assign \$33  = ~ (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:301" *) i_button_ffsync_i_buttons__pwr;
  assign \$37  = ~ (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:304" *) i_button_ffsync_i_buttons__pwr;
  assign \$45  = \$41  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *) \$43 ;
  assign \$47  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$49  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$51  = \$47  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:297" *) \$49 ;
  assign \$55  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$57  = \$53  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:300" *) \$55 ;
  assign \$5  = \$1  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *) \$3 ;
  assign \$59  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$63  = \$59  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:303" *) \$61 ;
  assign \$65  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$trigger$sync_1e6$1 ;
  assign \$67  = \$65  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) trigger;
  assign \$69  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$reset$sync_1e6$1 ;
  assign \$71  = \$69  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) reset;
  assign \$7  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  always @(posedge sync_1e6_clk)
    \$sample$s$reset$sync_1e6$1  <= reset;
  always @(posedge sync_1e6_clk)
    pin_led_7_led_7__o <= \pin_led_7_led_7__o$next ;
  always @(posedge sync_1e6_clk)
    ui__reset <= \ui__reset$next ;
  always @(posedge sync_1e6_clk)
    reset <= \reset$next ;
  always @(posedge sync_1e6_clk)
    ui__trigger <= \ui__trigger$next ;
  always @(posedge sync_1e6_clk)
    trigger <= \trigger$next ;
  always @(posedge sync_1e6_clk)
    tb_ui__reset <= \tb_ui__reset$next ;
  always @(posedge sync_1e6_clk)
    ui__done <= \ui__done$next ;
  always @(posedge sync_1e6_clk)
    tb_ui__trigger <= \tb_ui__trigger$next ;
  always @(posedge clk)
    pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o <= \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next ;
  always @(posedge clk)
    pin_esp32_spi_0__en_esp32_spi_0__en__o <= \pin_esp32_spi_0__en_esp32_spi_0__en__o$next ;
  always @(posedge sync_1e6_clk)
    \$sample$s$trigger$sync_1e6$1  <= trigger;
  always @(posedge clk)
    pin_uart_0__tx_uart_0__tx__o <= \pin_uart_0__tx_uart_0__tx__o$next ;
  always @(posedge clk)
    pin_esp32_spi_0__tx_esp32_spi_0__tx__o <= \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__right <= \i_button_ffsync_i_unsync_buttons__right$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__left <= \i_button_ffsync_i_unsync_buttons__left$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__down <= \i_button_ffsync_i_unsync_buttons__down$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__up <= \i_button_ffsync_i_unsync_buttons__up$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__fireB <= \i_button_ffsync_i_unsync_buttons__fireB$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__fireA <= \i_button_ffsync_i_unsync_buttons__fireA$next ;
  always @(posedge clk)
    i_button_ffsync_i_unsync_buttons__pwr <= \i_button_ffsync_i_unsync_buttons__pwr$next ;
  always @(posedge sync_1e6_clk)
    pin_led_0_led_0__o <= \pin_led_0_led_0__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_1_led_1__o <= \pin_led_1_led_1__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_2_led_2__o <= \pin_led_2_led_2__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_3_led_3__o <= \pin_led_3_led_3__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_4_led_4__o <= \pin_led_4_led_4__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_5_led_5__o <= \pin_led_5_led_5__o$next ;
  always @(posedge sync_1e6_clk)
    pin_led_6_led_6__o <= \pin_led_6_led_6__o$next ;
  i_button_ffsync i_button_ffsync (
    .clk(clk),
    .i_buttons__left(i_button_ffsync_i_buttons__left),
    .i_buttons__pwr(i_button_ffsync_i_buttons__pwr),
    .i_buttons__right(i_button_ffsync_i_buttons__right),
    .i_unsync_buttons__down(i_button_ffsync_i_unsync_buttons__down),
    .i_unsync_buttons__fireA(i_button_ffsync_i_unsync_buttons__fireA),
    .i_unsync_buttons__fireB(i_button_ffsync_i_unsync_buttons__fireB),
    .i_unsync_buttons__left(i_button_ffsync_i_unsync_buttons__left),
    .i_unsync_buttons__pwr(i_button_ffsync_i_unsync_buttons__pwr),
    .i_unsync_buttons__right(i_button_ffsync_i_unsync_buttons__right),
    .i_unsync_buttons__up(i_button_ffsync_i_unsync_buttons__up),
    .rst(rst)
  );
  pin_button_down_0 pin_button_down_0 (
    .button_down_0__i(pin_button_down_0_button_down_0__i),
    .button_down_0__io(button_down_0__io)
  );
  pin_button_fire_0 pin_button_fire_0 (
    .button_fire_0__i(pin_button_fire_0_button_fire_0__i),
    .button_fire_0__io(button_fire_0__io)
  );
  pin_button_fire_1 pin_button_fire_1 (
    .button_fire_1__i(pin_button_fire_1_button_fire_1__i),
    .button_fire_1__io(button_fire_1__io)
  );
  pin_button_left_0 pin_button_left_0 (
    .button_left_0__i(pin_button_left_0_button_left_0__i),
    .button_left_0__io(button_left_0__io)
  );
  pin_button_pwr_0 pin_button_pwr_0 (
    .button_pwr_0__i(pin_button_pwr_0_button_pwr_0__i),
    .button_pwr_0__io(button_pwr_0__io)
  );
  pin_button_right_0 pin_button_right_0 (
    .button_right_0__i(pin_button_right_0_button_right_0__i),
    .button_right_0__io(button_right_0__io)
  );
  pin_button_up_0 pin_button_up_0 (
    .button_up_0__i(pin_button_up_0_button_up_0__i),
    .button_up_0__io(button_up_0__io)
  );
  pin_clk25_0 pin_clk25_0 (
    .clk25_0__i(tb_clk25_0__i),
    .clk25_0__io(clk25_0__io)
  );
  pin_esp32_spi_0__en pin_esp32_spi_0__en (
    .esp32_spi_0__en__io(esp32_spi_0__en__io),
    .esp32_spi_0__en__o(pin_esp32_spi_0__en_esp32_spi_0__en__o)
  );
  pin_esp32_spi_0__gpio0 pin_esp32_spi_0__gpio0 (
    .esp32_spi_0__gpio0__io(esp32_spi_0__gpio0__io),
    .esp32_spi_0__gpio0__o(pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o)
  );
  pin_esp32_spi_0__gpio12_cipo pin_esp32_spi_0__gpio12_cipo (
    .esp32_spi_0__gpio12_cipo__io(esp32_spi_0__gpio12_cipo__io)
  );
  pin_esp32_spi_0__gpio16_sclk pin_esp32_spi_0__gpio16_sclk (
    .esp32_spi_0__gpio16_sclk__io(esp32_spi_0__gpio16_sclk__io)
  );
  pin_esp32_spi_0__gpio4_copi pin_esp32_spi_0__gpio4_copi (
    .esp32_spi_0__gpio4_copi__io(esp32_spi_0__gpio4_copi__io)
  );
  pin_esp32_spi_0__gpio5_cs pin_esp32_spi_0__gpio5_cs (
    .esp32_spi_0__gpio5_cs__io(esp32_spi_0__gpio5_cs__io)
  );
  pin_esp32_spi_0__rx pin_esp32_spi_0__rx (
    .esp32_spi_0__rx__i(pin_esp32_spi_0__rx_esp32_spi_0__rx__i),
    .esp32_spi_0__rx__io(esp32_spi_0__rx__io)
  );
  pin_esp32_spi_0__tx pin_esp32_spi_0__tx (
    .esp32_spi_0__tx__io(esp32_spi_0__tx__io),
    .esp32_spi_0__tx__o(pin_esp32_spi_0__tx_esp32_spi_0__tx__o)
  );
  pin_led_0 pin_led_0 (
    .led_0__io(led_0__io),
    .led_0__o(pin_led_0_led_0__o)
  );
  pin_led_1 pin_led_1 (
    .led_1__io(led_1__io),
    .led_1__o(pin_led_1_led_1__o)
  );
  pin_led_2 pin_led_2 (
    .led_2__io(led_2__io),
    .led_2__o(pin_led_2_led_2__o)
  );
  pin_led_3 pin_led_3 (
    .led_3__io(led_3__io),
    .led_3__o(pin_led_3_led_3__o)
  );
  pin_led_4 pin_led_4 (
    .led_4__io(led_4__io),
    .led_4__o(pin_led_4_led_4__o)
  );
  pin_led_5 pin_led_5 (
    .led_5__io(led_5__io),
    .led_5__o(pin_led_5_led_5__o)
  );
  pin_led_6 pin_led_6 (
    .led_6__io(led_6__io),
    .led_6__o(pin_led_6_led_6__o)
  );
  pin_led_7 pin_led_7 (
    .led_7__io(led_7__io),
    .led_7__o(pin_led_7_led_7__o)
  );
  pin_uart_0__dtr pin_uart_0__dtr (
    .uart_0__dtr__i(pin_uart_0__dtr_uart_0__dtr__i),
    .uart_0__dtr__io(uart_0__dtr__io)
  );
  pin_uart_0__rts pin_uart_0__rts (
    .uart_0__rts__i(pin_uart_0__rts_uart_0__rts__i),
    .uart_0__rts__io(uart_0__rts__io)
  );
  pin_uart_0__rx pin_uart_0__rx (
    .uart_0__rx__i(pin_uart_0__rx_uart_0__rx__i),
    .uart_0__rx__io(uart_0__rx__io)
  );
  pin_uart_0__tx pin_uart_0__tx (
    .uart_0__tx__io(uart_0__tx__io),
    .uart_0__tx__o(pin_uart_0__tx_uart_0__tx__o)
  );
  tb tb (
    .clk(clk),
    .clk25_0__i(tb_clk25_0__i),
    .leds(tb_leds),
    .rst(rst),
    .sync_1e6_clk(sync_1e6_clk),
    .sync_1e6_rst(sync_1e6_rst),
    .ui__done(tb_ui__done),
    .ui__reset(tb_ui__reset),
    .ui__trigger(tb_ui__trigger)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__pwr$next  = pin_button_pwr_0_button_pwr_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__pwr$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__fireA$next  = pin_button_fire_0_button_fire_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__fireA$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o;
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
    casez ({ \$63 , \$57 , \$51 , \$45  })
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" */
      4'b???1:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:297" */
      4'b??1?:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:300" */
      4'b?1??:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:303" */
      4'b1???:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h0;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \tb_ui__trigger$next  = ui__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \tb_ui__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \ui__done$next  = tb_ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \tb_ui__reset$next  = ui__reset;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \tb_ui__reset$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \trigger$next  = i_button_ffsync_i_buttons__left;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \ui__trigger$next  = \$67 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \reset$next  = i_button_ffsync_i_buttons__right;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \reset$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \ui__reset$next  = \$71 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \ui__reset$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    { \pin_led_7_led_7__o$next , \pin_led_6_led_6__o$next , \pin_led_5_led_5__o$next , \pin_led_4_led_4__o$next , \pin_led_3_led_3__o$next , \pin_led_2_led_2__o$next , \pin_led_1_led_1__o$next , \pin_led_0_led_0__o$next  } = tb_leds;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
        begin
          \pin_led_0_led_0__o$next  = 1'h0;
          \pin_led_1_led_1__o$next  = 1'h0;
          \pin_led_2_led_2__o$next  = 1'h0;
          \pin_led_3_led_3__o$next  = 1'h0;
          \pin_led_4_led_4__o$next  = 1'h0;
          \pin_led_5_led_5__o$next  = 1'h0;
          \pin_led_6_led_6__o$next  = 1'h0;
          \pin_led_7_led_7__o$next  = 1'h0;
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__fireB$next  = pin_button_fire_1_button_fire_1__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__fireB$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__up$next  = pin_button_up_0_button_up_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__up$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__down$next  = pin_button_down_0_button_down_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__down$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__left$next  = pin_button_left_0_button_left_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__left$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \i_button_ffsync_i_unsync_buttons__right$next  = pin_button_right_0_button_right_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__right$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next  = pin_uart_0__rx_uart_0__rx__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \pin_uart_0__tx_uart_0__tx__o$next  = pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_uart_0__tx_uart_0__tx__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$53 ) begin end
    \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = pin_esp32_spi_0__en_esp32_spi_0__en__o;
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" *)
    casez ({ \$23 , \$17 , \$11 , \$5  })
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:294" */
      4'b???1:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$27 ;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:297" */
      4'b??1?:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$31 ;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:300" */
      4'b?1??:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$35 ;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:303" */
      4'b1???:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$39 ;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = 1'h0;
    endcase
  end
  assign \$sample$s$reset$sync_1e6$1$next  = reset;
  assign \$sample$s$trigger$sync_1e6$1$next  = trigger;
  assign \$1  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$3  = pin_uart_0__rts_uart_0__rts__i;
  assign \$13  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$21  = pin_uart_0__rts_uart_0__rts__i;
  assign \$27  = \$25 ;
  assign \$31  = \$29 ;
  assign \$35  = 1'h0;
  assign \$39  = \$37 ;
  assign \$41  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$43  = pin_uart_0__rts_uart_0__rts__i;
  assign \$53  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$61  = pin_uart_0__rts_uart_0__rts__i;
endmodule
