/* Automatically generated by Amaranth 0.3. Do not edit. */
/* Generated by Yosys 0.13+3 (git sha1 61324cf55, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "top.tb.dut.delayer" *)
(* generator = "Amaranth" *)
module delayer(rst, start, done, clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$25  = 0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:21" *)
  wire \$1 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *)
  wire [16:0] \$10 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *)
  wire [16:0] \$11 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
  wire \$13 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:45" *)
  wire [16:0] \$15 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:45" *)
  wire [16:0] \$16 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$18 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$20 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *)
  wire \$22 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
  wire \$24 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$3 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
  wire \$5 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *)
  wire [16:0] \$7 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *)
  wire [16:0] \$8 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  input clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  reg [15:0] counter_out = 16'h0000;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:11" *)
  reg [15:0] \counter_out$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:13" *)
  output done;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
  reg [1:0] fsm_state = 2'h1;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:10" *)
  wire [15:0] reload;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  input rst;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  input start;
  assign \$11  = counter_out - (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:37" *) 1'h1;
  assign \$18  = counter_out > (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) 1'h0;
  assign \$1  = ! (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:21" *) fsm_state;
  assign \$20  = start & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) \$18 ;
  assign \$22  = counter_out == (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *) 1'h1;
  assign \$3  = counter_out > (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) 1'h0;
  assign \$5  = start & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *) \$3 ;
  assign \$8  = counter_out - (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:33" *) 1'h1;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    counter_out <= \counter_out$next ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$25 ) begin end
    \counter_out$next  = counter_out;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/1" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:23" */
      2'h1:
        begin
          \counter_out$next  = 16'h0fff;
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
          casez (\$5 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" */
            1'h1:
                \counter_out$next  = \$8 [15:0];
          endcase
        end
      /* \amaranth.decoding  = "RUNNING/2" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:36" */
      2'h2:
          \counter_out$next  = \$11 [15:0];
      /* \amaranth.decoding  = "DONE/0" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:41" */
      2'h0:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
          casez (\$13 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" */
            1'h1:
                \counter_out$next  = \$16 [15:0];
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \counter_out$next  = 16'h0000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$25 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:20" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "IDLE/1" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:23" */
      2'h1:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" *)
          casez (\$20 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:30" */
            1'h1:
                \fsm_state$next  = 2'h2;
          endcase
      /* \amaranth.decoding  = "RUNNING/2" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:36" */
      2'h2:
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" *)
          casez (\$22 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:38" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
      /* \amaranth.decoding  = "DONE/0" */
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:41" */
      2'h0:
          (* full_case = 32'd1 *)
          (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" *)
          casez (\$24 )
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:42" */
            1'h1:
                \fsm_state$next  = 2'h2;
            /* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:48" */
            default:
                \fsm_state$next  = 2'h1;
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h1;
    endcase
  end
  assign \$7  = \$8 ;
  assign \$10  = \$11 ;
  assign \$15  = \$16 ;
  assign reload = 16'h0000;
  assign done = \$1 ;
  assign \$13  = 1'h0;
  assign \$16  = 17'h1ffff;
  assign \$24  = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.tb.dut" *)
(* generator = "Amaranth" *)
module dut(rst, trigger, done, clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$26  = 0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  input clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:13" *)
  wire delayer_done;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/forks/gateware/examples/amlib/amlib/utils/timer.py:12" *)
  reg delayer_start;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:30" *)
  output done;
  reg done = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:30" *)
  reg \done$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  input rst;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:29" *)
  input trigger;
  always @(posedge clk)
    done <= \done$next ;
  delayer delayer (
    .clk(clk),
    .done(delayer_done),
    .rst(rst),
    .start(delayer_start)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$26 ) begin end
    delayer_start = 1'h0;
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:43" *)
    casez (trigger)
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:43" */
      1'h1:
          delayer_start = 1'h1;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$26 ) begin end
    \done$next  = delayer_done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \done$next  = 1'h0;
    endcase
  end
endmodule

(* \amaranth.hierarchy  = "top.pin_button_down_0" *)
(* generator = "Amaranth" *)
module pin_button_down_0(button_down_0__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  IB button_down_0_0 (
    .I(button_down_0__io),
    .O(button_down_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_0" *)
(* generator = "Amaranth" *)
module pin_button_fire_0(button_fire_0__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  IB button_fire_0_0 (
    .I(button_fire_0__io),
    .O(button_fire_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_1" *)
(* generator = "Amaranth" *)
module pin_button_fire_1(button_fire_1__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  IB button_fire_1_0 (
    .I(button_fire_1__io),
    .O(button_fire_1__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_left_0" *)
(* generator = "Amaranth" *)
module pin_button_left_0(button_left_0__io, button_left_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  IB button_left_0_0 (
    .I(button_left_0__io),
    .O(button_left_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_pwr_0" *)
(* generator = "Amaranth" *)
module pin_button_pwr_0(button_pwr_0__io, button_pwr_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire button_pwr_0__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) button_pwr_0__i_n;
  IB button_pwr_0_0 (
    .I(button_pwr_0__io),
    .O(button_pwr_0__i_n)
  );
  assign button_pwr_0__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_button_right_0" *)
(* generator = "Amaranth" *)
module pin_button_right_0(button_right_0__io, button_right_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  IB button_right_0_0 (
    .I(button_right_0__io),
    .O(button_right_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_up_0" *)
(* generator = "Amaranth" *)
module pin_button_up_0(button_up_0__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  IB button_up_0_0 (
    .I(button_up_0__io),
    .O(button_up_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_clk25_0" *)
(* generator = "Amaranth" *)
module pin_clk25_0(clk25_0__io, clk25_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  IB clk25_0_0 (
    .I(clk25_0__io),
    .O(clk25_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__en" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__en(esp32_spi_0__en__io, esp32_spi_0__en__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__en__o;
  OB esp32_spi_0__en_0 (
    .I(esp32_spi_0__en__o),
    .O(esp32_spi_0__en__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio0" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio0(esp32_spi_0__gpio0__io, esp32_spi_0__gpio0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:531" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__gpio0__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__oe;
  BB esp32_spi_0__gpio0_0 (
    .B(esp32_spi_0__gpio0__io),
    .I(esp32_spi_0__gpio0__o),
    .O(esp32_spi_0__gpio0__i),
    .T(1'h1)
  );
  assign esp32_spi_0__gpio0__oe = 1'h0;
  assign \$1  = 1'h1;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio12_cipo" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio12_cipo(esp32_spi_0__gpio12_cipo__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio12_cipo__o;
  OB esp32_spi_0__gpio12_cipo_0 (
    .I(1'h0),
    .O(esp32_spi_0__gpio12_cipo__io)
  );
  assign esp32_spi_0__gpio12_cipo__o = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio16_sclk" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio16_sclk(esp32_spi_0__gpio16_sclk__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio16_sclk__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  IB esp32_spi_0__gpio16_sclk_0 (
    .I(esp32_spi_0__gpio16_sclk__io),
    .O(esp32_spi_0__gpio16_sclk__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio4_copi" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio4_copi(esp32_spi_0__gpio4_copi__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio4_copi__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  IB esp32_spi_0__gpio4_copi_0 (
    .I(esp32_spi_0__gpio4_copi__io),
    .O(esp32_spi_0__gpio4_copi__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio5_cs" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio5_cs(esp32_spi_0__gpio5_cs__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio5_cs__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire esp32_spi_0__gpio5_cs__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) esp32_spi_0__gpio5_cs__i_n;
  IB esp32_spi_0__gpio5_cs_0 (
    .I(esp32_spi_0__gpio5_cs__io),
    .O(esp32_spi_0__gpio5_cs__i_n)
  );
  assign esp32_spi_0__gpio5_cs__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__rx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__rx(esp32_spi_0__rx__io, esp32_spi_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  IB esp32_spi_0__rx_0 (
    .I(esp32_spi_0__rx__io),
    .O(esp32_spi_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__tx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__tx(esp32_spi_0__tx__io, esp32_spi_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__tx__o;
  OB esp32_spi_0__tx_0 (
    .I(esp32_spi_0__tx__o),
    .O(esp32_spi_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_0" *)
(* generator = "Amaranth" *)
module pin_led_0(led_0__io, led_0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_0__o;
  OB led_0_0 (
    .I(led_0__o),
    .O(led_0__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_1" *)
(* generator = "Amaranth" *)
module pin_led_1(led_1__io, led_1__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_1__o;
  OB led_1_0 (
    .I(led_1__o),
    .O(led_1__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_2" *)
(* generator = "Amaranth" *)
module pin_led_2(led_2__io, led_2__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_2__o;
  OB led_2_0 (
    .I(led_2__o),
    .O(led_2__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_3" *)
(* generator = "Amaranth" *)
module pin_led_3(led_3__io, led_3__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_3__o;
  OB led_3_0 (
    .I(led_3__o),
    .O(led_3__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_4" *)
(* generator = "Amaranth" *)
module pin_led_4(led_4__io, led_4__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_4__o;
  OB led_4_0 (
    .I(led_4__o),
    .O(led_4__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_5" *)
(* generator = "Amaranth" *)
module pin_led_5(led_5__io, led_5__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_5__o;
  OB led_5_0 (
    .I(led_5__o),
    .O(led_5__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_6" *)
(* generator = "Amaranth" *)
module pin_led_6(led_6__io, led_6__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_6__o;
  OB led_6_0 (
    .I(led_6__o),
    .O(led_6__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_7" *)
(* generator = "Amaranth" *)
module pin_led_7(led_7__io, led_7__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_7__o;
  OB led_7_0 (
    .I(led_7__o),
    .O(led_7__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__dtr" *)
(* generator = "Amaranth" *)
module pin_uart_0__dtr(uart_0__dtr__io, uart_0__dtr__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  IB uart_0__dtr_0 (
    .I(uart_0__dtr__io),
    .O(uart_0__dtr__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rts" *)
(* generator = "Amaranth" *)
module pin_uart_0__rts(uart_0__rts__io, uart_0__rts__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  IB uart_0__rts_0 (
    .I(uart_0__rts__io),
    .O(uart_0__rts__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rx" *)
(* generator = "Amaranth" *)
module pin_uart_0__rx(uart_0__rx__io, uart_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  IB uart_0__rx_0 (
    .I(uart_0__rx__io),
    .O(uart_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__tx" *)
(* generator = "Amaranth" *)
module pin_uart_0__tx(uart_0__tx__io, uart_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input uart_0__tx__o;
  OB uart_0__tx_0 (
    .I(uart_0__tx__o),
    .O(uart_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.tb" *)
(* generator = "Amaranth" *)
module tb(dut_test_io__trigger, dut_test_io__done, dut_test_io__reset, leds, rst, clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$27  = 0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$10 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *)
  wire [8:0] \$12 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *)
  wire [8:0] \$13 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$15 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$17 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *)
  wire [8:0] \$19 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *)
  wire [8:0] \$20 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$3 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *)
  wire [8:0] \$5 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *)
  wire [8:0] \$6 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$8 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg \$sample$s$dut_test_io__done$sync$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  wire \$sample$s$dut_test_io__done$sync$1$next ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg \$sample$s$dut_test_io__reset$sync$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  wire \$sample$s$dut_test_io__reset$sync$1$next ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg \$sample$s$dut_test_io__trigger$sync$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  wire \$sample$s$dut_test_io__trigger$sync$1$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  input clk;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:30" *)
  wire dut_done;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  output dut_test_io__done;
  reg dut_test_io__done = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg \dut_test_io__done$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  input dut_test_io__reset;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  input dut_test_io__trigger;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:29" *)
  reg dut_trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:29" *)
  reg \dut_trigger$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:68" *)
  output [7:0] leds;
  reg [7:0] leds = 8'h00;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:68" *)
  reg [7:0] \leds$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  input rst;
  assign \$10  = \$8  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) dut_test_io__done;
  assign \$13  = leds + (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *) 1'h1;
  assign \$15  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$dut_test_io__reset$sync$1 ;
  assign \$17  = \$15  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) dut_test_io__reset;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$dut_test_io__trigger$sync$1 ;
  assign \$20  = leds + (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *) 1'h1;
  assign \$3  = \$1  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) dut_test_io__trigger;
  assign \$6  = leds + (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:86" *) 1'h1;
  assign \$8  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$dut_test_io__done$sync$1 ;
  always @(posedge clk)
    \$sample$s$dut_test_io__reset$sync$1  <= dut_test_io__reset;
  always @(posedge clk)
    \$sample$s$dut_test_io__done$sync$1  <= dut_test_io__done;
  always @(posedge clk)
    \$sample$s$dut_test_io__trigger$sync$1  <= dut_test_io__trigger;
  always @(posedge clk)
    leds <= \leds$next ;
  always @(posedge clk)
    dut_test_io__done <= \dut_test_io__done$next ;
  always @(posedge clk)
    dut_trigger <= \dut_trigger$next ;
  dut dut (
    .clk(clk),
    .done(dut_done),
    .rst(rst),
    .trigger(dut_trigger)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$27 ) begin end
    \dut_trigger$next  = dut_test_io__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \dut_trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$27 ) begin end
    \dut_test_io__done$next  = dut_done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \dut_test_io__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$27 ) begin end
    (* full_case = 32'd1 *)
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
    casez (\$3 )
    endcase
    (* full_case = 32'd1 *)
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
    casez (\$10 )
    endcase
    (* full_case = 32'd1 *)
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
    casez (\$17 )
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" */
      1'h1:
          \leds$next  = \$20 [7:0];
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:87" */
      default:
          \leds$next  = leds;
    endcase
  end
  assign \$5  = \$6 ;
  assign \$12  = \$13 ;
  assign \$19  = \$20 ;
  assign \$sample$s$dut_test_io__reset$sync$1$next  = dut_test_io__reset;
  assign \$sample$s$dut_test_io__done$sync$1$next  = dut_test_io__done;
  assign \$sample$s$dut_test_io__trigger$sync$1$next  = dut_test_io__trigger;
endmodule

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(led_0__io, led_1__io, led_2__io, led_3__io, led_4__io, led_5__io, led_6__io, led_7__io, esp32_spi_0__en__io, esp32_spi_0__tx__io, esp32_spi_0__rx__io, esp32_spi_0__gpio4_copi__io, esp32_spi_0__gpio5_cs__io, esp32_spi_0__gpio12_cipo__io, esp32_spi_0__gpio16_sclk__io, uart_0__rx__io, uart_0__tx__io, uart_0__rts__io, uart_0__dtr__io, clk25_0__io, button_pwr_0__io
, button_fire_0__io, button_fire_1__io, button_up_0__io, button_down_0__io, button_left_0__io, button_right_0__io, esp32_spi_0__gpio0__io);
  reg \$auto$verilog_backend.cc:2083:dump_module$28  = 0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
  wire \$1 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:244" *)
  wire \$11 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$13 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$15 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:247" *)
  wire \$17 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$19 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$21 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:250" *)
  wire \$23 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$25 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:242" *)
  wire \$27 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$29 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
  wire \$3 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:245" *)
  wire \$31 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$33 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:248" *)
  wire \$35 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$37 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:251" *)
  wire \$39 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
  wire \$41 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
  wire \$43 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
  wire \$45 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$47 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$49 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
  wire \$5 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:244" *)
  wire \$51 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$53 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$55 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:247" *)
  wire \$57 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$59 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$61 ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:250" *)
  wire \$63 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$65 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$67 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$69 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$7 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$71 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$9 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:276" *)
  reg \$sample$s$reset$sync$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:276" *)
  wire \$sample$s$reset$sync$1$next ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:275" *)
  reg \$sample$s$trigger$sync$1  = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:275" *)
  wire \$sample$s$trigger$sync$1$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  wire clk;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_left_0_button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_pwr_0_button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_right_0_button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_clk25_0_clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__en_esp32_spi_0__en__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_esp32_spi_0__tx_esp32_spi_0__tx__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_0_led_0__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_0_led_0__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_1_led_1__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_1_led_1__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_2_led_2__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_2_led_2__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_3_led_3__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_3_led_3__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_4_led_4__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_4_led_4__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_5_led_5__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_5_led_5__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_6_led_6__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_6_led_6__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_led_7_led_7__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_led_7_led_7__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__dtr_uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rts_uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rx_uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__tx_uart_0__tx__o;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:276" *)
  wire reset;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:218" *)
  wire rst;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:259" *)
  reg sim_test_io__done = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:259" *)
  reg \sim_test_io__done$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:259" *)
  reg sim_test_io__reset = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:259" *)
  reg \sim_test_io__reset$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:259" *)
  reg sim_test_io__trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:259" *)
  reg \sim_test_io__trigger$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  wire tb_dut_test_io__done;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg tb_dut_test_io__reset = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg \tb_dut_test_io__reset$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg tb_dut_test_io__trigger = 1'h0;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:85" *)
  reg \tb_dut_test_io__trigger$next ;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:68" *)
  wire [7:0] tb_leds;
  (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:275" *)
  wire trigger;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  assign \$9  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$11  = \$7  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:244" *) \$9 ;
  assign \$15  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$17  = \$13  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:247" *) \$15 ;
  assign \$19  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$23  = \$19  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:250" *) \$21 ;
  assign \$25  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_button_pwr_0_button_pwr_0__i;
  assign \$29  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_button_pwr_0_button_pwr_0__i;
  assign \$33  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_button_pwr_0_button_pwr_0__i;
  assign \$37  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_button_pwr_0_button_pwr_0__i;
  assign \$45  = \$41  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *) \$43 ;
  assign \$47  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$49  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$51  = \$47  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:244" *) \$49 ;
  assign \$55  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$57  = \$53  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:247" *) \$55 ;
  assign \$5  = \$1  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *) \$3 ;
  assign \$59  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$63  = \$59  & (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:250" *) \$61 ;
  assign \$65  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$trigger$sync$1 ;
  assign \$67  = \$65  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) trigger;
  assign \$69  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$reset$sync$1 ;
  assign \$71  = \$69  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) reset;
  assign \$7  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  always @(posedge clk)
    \$sample$s$reset$sync$1  <= pin_button_right_0_button_right_0__i;
  always @(posedge clk)
    pin_led_7_led_7__o <= \pin_led_7_led_7__o$next ;
  always @(posedge clk)
    sim_test_io__reset <= \sim_test_io__reset$next ;
  always @(posedge clk)
    sim_test_io__trigger <= \sim_test_io__trigger$next ;
  always @(posedge clk)
    tb_dut_test_io__reset <= \tb_dut_test_io__reset$next ;
  always @(posedge clk)
    sim_test_io__done <= \sim_test_io__done$next ;
  always @(posedge clk)
    tb_dut_test_io__trigger <= \tb_dut_test_io__trigger$next ;
  always @(posedge clk)
    \$sample$s$trigger$sync$1  <= pin_button_left_0_button_left_0__i;
  always @(posedge clk)
    pin_led_0_led_0__o <= \pin_led_0_led_0__o$next ;
  always @(posedge clk)
    pin_led_1_led_1__o <= \pin_led_1_led_1__o$next ;
  always @(posedge clk)
    pin_led_2_led_2__o <= \pin_led_2_led_2__o$next ;
  always @(posedge clk)
    pin_led_3_led_3__o <= \pin_led_3_led_3__o$next ;
  always @(posedge clk)
    pin_led_4_led_4__o <= \pin_led_4_led_4__o$next ;
  always @(posedge clk)
    pin_led_5_led_5__o <= \pin_led_5_led_5__o$next ;
  always @(posedge clk)
    pin_led_6_led_6__o <= \pin_led_6_led_6__o$next ;
  pin_button_down_0 pin_button_down_0 (
    .button_down_0__io(button_down_0__io)
  );
  pin_button_fire_0 pin_button_fire_0 (
    .button_fire_0__io(button_fire_0__io)
  );
  pin_button_fire_1 pin_button_fire_1 (
    .button_fire_1__io(button_fire_1__io)
  );
  pin_button_left_0 pin_button_left_0 (
    .button_left_0__i(pin_button_left_0_button_left_0__i),
    .button_left_0__io(button_left_0__io)
  );
  pin_button_pwr_0 pin_button_pwr_0 (
    .button_pwr_0__i(pin_button_pwr_0_button_pwr_0__i),
    .button_pwr_0__io(button_pwr_0__io)
  );
  pin_button_right_0 pin_button_right_0 (
    .button_right_0__i(pin_button_right_0_button_right_0__i),
    .button_right_0__io(button_right_0__io)
  );
  pin_button_up_0 pin_button_up_0 (
    .button_up_0__io(button_up_0__io)
  );
  pin_clk25_0 pin_clk25_0 (
    .clk25_0__i(pin_clk25_0_clk25_0__i),
    .clk25_0__io(clk25_0__io)
  );
  pin_esp32_spi_0__en pin_esp32_spi_0__en (
    .esp32_spi_0__en__io(esp32_spi_0__en__io),
    .esp32_spi_0__en__o(pin_esp32_spi_0__en_esp32_spi_0__en__o)
  );
  pin_esp32_spi_0__gpio0 pin_esp32_spi_0__gpio0 (
    .esp32_spi_0__gpio0__io(esp32_spi_0__gpio0__io),
    .esp32_spi_0__gpio0__o(pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o)
  );
  pin_esp32_spi_0__gpio12_cipo pin_esp32_spi_0__gpio12_cipo (
    .esp32_spi_0__gpio12_cipo__io(esp32_spi_0__gpio12_cipo__io)
  );
  pin_esp32_spi_0__gpio16_sclk pin_esp32_spi_0__gpio16_sclk (
    .esp32_spi_0__gpio16_sclk__io(esp32_spi_0__gpio16_sclk__io)
  );
  pin_esp32_spi_0__gpio4_copi pin_esp32_spi_0__gpio4_copi (
    .esp32_spi_0__gpio4_copi__io(esp32_spi_0__gpio4_copi__io)
  );
  pin_esp32_spi_0__gpio5_cs pin_esp32_spi_0__gpio5_cs (
    .esp32_spi_0__gpio5_cs__io(esp32_spi_0__gpio5_cs__io)
  );
  pin_esp32_spi_0__rx pin_esp32_spi_0__rx (
    .esp32_spi_0__rx__i(pin_esp32_spi_0__rx_esp32_spi_0__rx__i),
    .esp32_spi_0__rx__io(esp32_spi_0__rx__io)
  );
  pin_esp32_spi_0__tx pin_esp32_spi_0__tx (
    .esp32_spi_0__tx__io(esp32_spi_0__tx__io),
    .esp32_spi_0__tx__o(pin_esp32_spi_0__tx_esp32_spi_0__tx__o)
  );
  pin_led_0 pin_led_0 (
    .led_0__io(led_0__io),
    .led_0__o(pin_led_0_led_0__o)
  );
  pin_led_1 pin_led_1 (
    .led_1__io(led_1__io),
    .led_1__o(pin_led_1_led_1__o)
  );
  pin_led_2 pin_led_2 (
    .led_2__io(led_2__io),
    .led_2__o(pin_led_2_led_2__o)
  );
  pin_led_3 pin_led_3 (
    .led_3__io(led_3__io),
    .led_3__o(pin_led_3_led_3__o)
  );
  pin_led_4 pin_led_4 (
    .led_4__io(led_4__io),
    .led_4__o(pin_led_4_led_4__o)
  );
  pin_led_5 pin_led_5 (
    .led_5__io(led_5__io),
    .led_5__o(pin_led_5_led_5__o)
  );
  pin_led_6 pin_led_6 (
    .led_6__io(led_6__io),
    .led_6__o(pin_led_6_led_6__o)
  );
  pin_led_7 pin_led_7 (
    .led_7__io(led_7__io),
    .led_7__o(pin_led_7_led_7__o)
  );
  pin_uart_0__dtr pin_uart_0__dtr (
    .uart_0__dtr__i(pin_uart_0__dtr_uart_0__dtr__i),
    .uart_0__dtr__io(uart_0__dtr__io)
  );
  pin_uart_0__rts pin_uart_0__rts (
    .uart_0__rts__i(pin_uart_0__rts_uart_0__rts__i),
    .uart_0__rts__io(uart_0__rts__io)
  );
  pin_uart_0__rx pin_uart_0__rx (
    .uart_0__rx__i(pin_uart_0__rx_uart_0__rx__i),
    .uart_0__rx__io(uart_0__rx__io)
  );
  pin_uart_0__tx pin_uart_0__tx (
    .uart_0__tx__io(uart_0__tx__io),
    .uart_0__tx__o(pin_uart_0__tx_uart_0__tx__o)
  );
  tb tb (
    .clk(clk),
    .dut_test_io__done(tb_dut_test_io__done),
    .dut_test_io__reset(tb_dut_test_io__reset),
    .dut_test_io__trigger(tb_dut_test_io__trigger),
    .leds(tb_leds),
    .rst(1'h0)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    \sim_test_io__trigger$next  = \$67 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sim_test_io__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    \sim_test_io__reset$next  = \$71 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sim_test_io__reset$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    { \pin_led_7_led_7__o$next , \pin_led_6_led_6__o$next , \pin_led_5_led_5__o$next , \pin_led_4_led_4__o$next , \pin_led_3_led_3__o$next , \pin_led_2_led_2__o$next , \pin_led_1_led_1__o$next , \pin_led_0_led_0__o$next  } = tb_leds;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
        begin
          \pin_led_0_led_0__o$next  = 1'h0;
          \pin_led_1_led_1__o$next  = 1'h0;
          \pin_led_2_led_2__o$next  = 1'h0;
          \pin_led_3_led_3__o$next  = 1'h0;
          \pin_led_4_led_4__o$next  = 1'h0;
          \pin_led_5_led_5__o$next  = 1'h0;
          \pin_led_6_led_6__o$next  = 1'h0;
          \pin_led_7_led_7__o$next  = 1'h0;
        end
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    pin_esp32_spi_0__en_esp32_spi_0__en__o = 1'h0;
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
    casez ({ \$23 , \$17 , \$11 , \$5  })
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" */
      4'b???1:
          pin_esp32_spi_0__en_esp32_spi_0__en__o = \$27 ;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:244" */
      4'b??1?:
          pin_esp32_spi_0__en_esp32_spi_0__en__o = \$31 ;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:247" */
      4'b?1??:
          pin_esp32_spi_0__en_esp32_spi_0__en__o = \$35 ;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:250" */
      4'b1???:
          pin_esp32_spi_0__en_esp32_spi_0__en__o = \$39 ;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h0;
    (* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" *)
    casez ({ \$63 , \$57 , \$51 , \$45  })
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:241" */
      4'b???1:
          pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h1;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:244" */
      4'b??1?:
          pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h1;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:247" */
      4'b?1??:
          pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h1;
      /* src = "tests/ulx3s_gui_test/fpga_gateware/feb17_restructure_tests/test1_amlib_timers.py:250" */
      4'b1???:
          pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    \tb_dut_test_io__trigger$next  = sim_test_io__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \tb_dut_test_io__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    \sim_test_io__done$next  = tb_dut_test_io__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sim_test_io__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$28 ) begin end
    \tb_dut_test_io__reset$next  = sim_test_io__reset;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \tb_dut_test_io__reset$next  = 1'h0;
    endcase
  end
  assign rst = 1'h0;
  assign \$sample$s$reset$sync$1$next  = reset;
  assign \$sample$s$trigger$sync$1$next  = trigger;
  assign reset = pin_button_right_0_button_right_0__i;
  assign trigger = pin_button_left_0_button_left_0__i;
  assign pin_uart_0__tx_uart_0__tx__o = pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
  assign pin_esp32_spi_0__tx_esp32_spi_0__tx__o = pin_uart_0__rx_uart_0__rx__i;
  assign clk = pin_clk25_0_clk25_0__i;
  assign \$1  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$3  = pin_uart_0__rts_uart_0__rts__i;
  assign \$13  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$21  = pin_uart_0__rts_uart_0__rts__i;
  assign \$27  = \$25 ;
  assign \$31  = \$29 ;
  assign \$35  = 1'h0;
  assign \$39  = \$37 ;
  assign \$41  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$43  = pin_uart_0__rts_uart_0__rts__i;
  assign \$53  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$61  = pin_uart_0__rts_uart_0__rts__i;
endmodule
