/* Automatically generated by Amaranth 0.4.dev7+g02364a4. Do not edit. */
/* Generated by Yosys 0.13+3 (git sha1 61324cf55, clang 10.0.0-4ubuntu1 -fPIC -Os) */

(* \amaranth.hierarchy  = "top.tb.delayer" *)
(* generator = "Amaranth" *)
module delayer(rst, ui__done, ui__inactive, ui__load, clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$1  = 0;
  (* src = "amaram/common/Delayer.py:148" *)
  wire [12:0] \$1 ;
  (* src = "amaram/common/Delayer.py:154" *)
  wire \$10 ;
  (* src = "amaram/common/Delayer.py:149" *)
  wire \$12 ;
  (* src = "amaram/common/Delayer.py:150" *)
  wire \$14 ;
  (* src = "amaram/common/Delayer.py:148" *)
  wire [12:0] \$2 ;
  (* src = "amaram/common/Delayer.py:144" *)
  wire [12:0] \$4 ;
  (* src = "amaram/common/Delayer.py:148" *)
  wire [12:0] \$6 ;
  (* src = "amaram/common/Delayer.py:148" *)
  wire \$7 ;
  (* src = "amaram/common/Delayer.py:137" *)
  reg _ui__done = 1'h0;
  (* src = "amaram/common/Delayer.py:137" *)
  reg \_ui__done$next ;
  (* src = "amaram/common/Delayer.py:137" *)
  reg _ui__inactive = 1'h0;
  (* src = "amaram/common/Delayer.py:137" *)
  reg \_ui__inactive$next ;
  (* src = "amaram/common/Delayer.py:137" *)
  reg [11:0] _ui__load = 12'h000;
  (* src = "amaram/common/Delayer.py:137" *)
  reg [11:0] \_ui__load$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input clk;
  (* src = "amaram/common/Delayer.py:144" *)
  reg [11:0] countdown = 12'h000;
  (* src = "amaram/common/Delayer.py:144" *)
  reg [11:0] \countdown$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input rst;
  (* src = "amaram/common/Delayer.py:79" *)
  output ui__done;
  reg ui__done = 1'h0;
  (* src = "amaram/common/Delayer.py:79" *)
  reg \ui__done$next ;
  (* src = "amaram/common/Delayer.py:79" *)
  output ui__inactive;
  reg ui__inactive = 1'h0;
  (* src = "amaram/common/Delayer.py:79" *)
  reg \ui__inactive$next ;
  (* src = "amaram/common/Delayer.py:79" *)
  input [11:0] ui__load;
  assign \$10  = | (* src = "amaram/common/Delayer.py:154" *) _ui__load;
  assign \$12  = countdown == (* src = "amaram/common/Delayer.py:149" *) 1'h1;
  assign \$14  = ! (* src = "amaram/common/Delayer.py:150" *) countdown;
  always @(posedge clk)
    ui__done <= \ui__done$next ;
  always @(posedge clk)
    ui__inactive <= \ui__inactive$next ;
  always @(posedge clk)
    _ui__load <= \_ui__load$next ;
  always @(posedge clk)
    countdown <= \countdown$next ;
  always @(posedge clk)
    _ui__done <= \_ui__done$next ;
  always @(posedge clk)
    _ui__inactive <= \_ui__inactive$next ;
  assign \$2  = countdown - (* src = "amaram/common/Delayer.py:148" *) 1'h1;
  assign \$4  = + (* src = "amaram/common/Delayer.py:144" *) countdown;
  assign \$7  = countdown > (* src = "amaram/common/Delayer.py:148" *) 1'h0;
  assign \$6  = \$7  ? (* src = "amaram/common/Delayer.py:148" *) \$2  : \$4 ;
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \ui__done$next  = _ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \ui__inactive$next  = _ui__inactive;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__inactive$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \_ui__load$next  = ui__load;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__load$next  = 12'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \countdown$next  = \$6 [11:0];
    (* src = "amaram/common/Delayer.py:154" *)
    casez (\$10 )
      /* src = "amaram/common/Delayer.py:154" */
      1'h1:
          \countdown$next  = _ui__load;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \countdown$next  = 12'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \_ui__done$next  = \$12 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$1 ) begin end
    \_ui__inactive$next  = \$14 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__inactive$next  = 1'h0;
    endcase
  end
  assign \$1  = \$6 ;
endmodule

(* \amaranth.hierarchy  = "top.i_button_ffsync" *)
(* generator = "Amaranth" *)
module i_button_ffsync(i_unsync_buttons__pwr, i_unsync_buttons__fireA, i_unsync_buttons__fireB, i_unsync_buttons__up, i_unsync_buttons__down, i_unsync_buttons__left, i_unsync_buttons__right, i_buttons__pwr, i_buttons__left, rst, i_buttons__right, clk);
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input clk;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__down;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__fireA;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__fireB;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  output i_buttons__left;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  output i_buttons__pwr;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  output i_buttons__right;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_buttons__up;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__down;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__fireA;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__fireB;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__left;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__pwr;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__right;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  input i_unsync_buttons__up;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input rst;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  reg [6:0] stage0 = 7'h00;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  wire [6:0] \stage0$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  reg [6:0] stage1 = 7'h00;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/lib/cdc.py:89" *)
  wire [6:0] \stage1$next ;
  always @(posedge clk)
    stage0 <= \stage0$next ;
  always @(posedge clk)
    stage1 <= \stage1$next ;
  assign { i_buttons__right, i_buttons__left, i_buttons__down, i_buttons__up, i_buttons__fireB, i_buttons__fireA, i_buttons__pwr } = stage1;
  assign \stage1$next  = stage0;
  assign \stage0$next  = { i_unsync_buttons__right, i_unsync_buttons__left, i_unsync_buttons__down, i_unsync_buttons__up, i_unsync_buttons__fireB, i_unsync_buttons__fireA, i_unsync_buttons__pwr };
endmodule

(* \amaranth.hierarchy  = "top.pin_button_down_0" *)
(* generator = "Amaranth" *)
module pin_button_down_0(button_down_0__io, button_down_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  IB button_down_0_0 (
    .I(button_down_0__io),
    .O(button_down_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_0" *)
(* generator = "Amaranth" *)
module pin_button_fire_0(button_fire_0__io, button_fire_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  IB button_fire_0_0 (
    .I(button_fire_0__io),
    .O(button_fire_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_fire_1" *)
(* generator = "Amaranth" *)
module pin_button_fire_1(button_fire_1__io, button_fire_1__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  IB button_fire_1_0 (
    .I(button_fire_1__io),
    .O(button_fire_1__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_left_0" *)
(* generator = "Amaranth" *)
module pin_button_left_0(button_left_0__io, button_left_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  IB button_left_0_0 (
    .I(button_left_0__io),
    .O(button_left_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_pwr_0" *)
(* generator = "Amaranth" *)
module pin_button_pwr_0(button_pwr_0__io, button_pwr_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire button_pwr_0__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) button_pwr_0__i_n;
  IB button_pwr_0_0 (
    .I(button_pwr_0__io),
    .O(button_pwr_0__i_n)
  );
  assign button_pwr_0__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_button_right_0" *)
(* generator = "Amaranth" *)
module pin_button_right_0(button_right_0__io, button_right_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  IB button_right_0_0 (
    .I(button_right_0__io),
    .O(button_right_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_button_up_0" *)
(* generator = "Amaranth" *)
module pin_button_up_0(button_up_0__io, button_up_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  IB button_up_0_0 (
    .I(button_up_0__io),
    .O(button_up_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_clk25_0" *)
(* generator = "Amaranth" *)
module pin_clk25_0(clk25_0__io, clk25_0__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  IB clk25_0_0 (
    .I(clk25_0__io),
    .O(clk25_0__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__en" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__en(esp32_spi_0__en__io, esp32_spi_0__en__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__en__o;
  OB esp32_spi_0__en_0 (
    .I(esp32_spi_0__en__o),
    .O(esp32_spi_0__en__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio0" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio0(esp32_spi_0__gpio0__io, esp32_spi_0__gpio0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:531" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__gpio0__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio0__oe;
  BB esp32_spi_0__gpio0_0 (
    .B(esp32_spi_0__gpio0__io),
    .I(esp32_spi_0__gpio0__o),
    .O(esp32_spi_0__gpio0__i),
    .T(1'h1)
  );
  assign esp32_spi_0__gpio0__oe = 1'h0;
  assign \$1  = 1'h1;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio12_cipo" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio12_cipo(esp32_spi_0__gpio12_cipo__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio12_cipo__o;
  OB esp32_spi_0__gpio12_cipo_0 (
    .I(1'h0),
    .O(esp32_spi_0__gpio12_cipo__io)
  );
  assign esp32_spi_0__gpio12_cipo__o = 1'h0;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio16_sclk" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio16_sclk(esp32_spi_0__gpio16_sclk__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio16_sclk__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  IB esp32_spi_0__gpio16_sclk_0 (
    .I(esp32_spi_0__gpio16_sclk__io),
    .O(esp32_spi_0__gpio16_sclk__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio4_copi" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio4_copi(esp32_spi_0__gpio4_copi__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio4_copi__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  IB esp32_spi_0__gpio4_copi_0 (
    .I(esp32_spi_0__gpio4_copi__io),
    .O(esp32_spi_0__gpio4_copi__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__gpio5_cs" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__gpio5_cs(esp32_spi_0__gpio5_cs__io);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *)
  wire \$1 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire esp32_spi_0__gpio5_cs__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:464" *)
  wire esp32_spi_0__gpio5_cs__i_n;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  assign \$1  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/vendor/lattice_ecp5.py:465" *) esp32_spi_0__gpio5_cs__i_n;
  IB esp32_spi_0__gpio5_cs_0 (
    .I(esp32_spi_0__gpio5_cs__io),
    .O(esp32_spi_0__gpio5_cs__i_n)
  );
  assign esp32_spi_0__gpio5_cs__i = \$1 ;
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__rx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__rx(esp32_spi_0__rx__io, esp32_spi_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  IB esp32_spi_0__rx_0 (
    .I(esp32_spi_0__rx__io),
    .O(esp32_spi_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_esp32_spi_0__tx" *)
(* generator = "Amaranth" *)
module pin_esp32_spi_0__tx(esp32_spi_0__tx__io, esp32_spi_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input esp32_spi_0__tx__o;
  OB esp32_spi_0__tx_0 (
    .I(esp32_spi_0__tx__o),
    .O(esp32_spi_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_0" *)
(* generator = "Amaranth" *)
module pin_led_0(led_0__io, led_0__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_0__o;
  OB led_0_0 (
    .I(led_0__o),
    .O(led_0__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_1" *)
(* generator = "Amaranth" *)
module pin_led_1(led_1__io, led_1__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_1__o;
  OB led_1_0 (
    .I(led_1__o),
    .O(led_1__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_2" *)
(* generator = "Amaranth" *)
module pin_led_2(led_2__io, led_2__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_2__o;
  OB led_2_0 (
    .I(led_2__o),
    .O(led_2__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_3" *)
(* generator = "Amaranth" *)
module pin_led_3(led_3__io, led_3__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_3__o;
  OB led_3_0 (
    .I(led_3__o),
    .O(led_3__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_4" *)
(* generator = "Amaranth" *)
module pin_led_4(led_4__io, led_4__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_4__o;
  OB led_4_0 (
    .I(led_4__o),
    .O(led_4__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_5" *)
(* generator = "Amaranth" *)
module pin_led_5(led_5__io, led_5__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_5__o;
  OB led_5_0 (
    .I(led_5__o),
    .O(led_5__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_6" *)
(* generator = "Amaranth" *)
module pin_led_6(led_6__io, led_6__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_6__o;
  OB led_6_0 (
    .I(led_6__o),
    .O(led_6__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_led_7" *)
(* generator = "Amaranth" *)
module pin_led_7(led_7__io, led_7__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input led_7__o;
  OB led_7_0 (
    .I(led_7__o),
    .O(led_7__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__dtr" *)
(* generator = "Amaranth" *)
module pin_uart_0__dtr(uart_0__dtr__io, uart_0__dtr__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  IB uart_0__dtr_0 (
    .I(uart_0__dtr__io),
    .O(uart_0__dtr__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rts" *)
(* generator = "Amaranth" *)
module pin_uart_0__rts(uart_0__rts__io, uart_0__rts__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  IB uart_0__rts_0 (
    .I(uart_0__rts__io),
    .O(uart_0__rts__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__rx" *)
(* generator = "Amaranth" *)
module pin_uart_0__rx(uart_0__rx__io, uart_0__rx__i);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  output uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  IB uart_0__rx_0 (
    .I(uart_0__rx__io),
    .O(uart_0__rx__i)
  );
endmodule

(* \amaranth.hierarchy  = "top.pin_uart_0__tx" *)
(* generator = "Amaranth" *)
module pin_uart_0__tx(uart_0__tx__io, uart_0__tx__o);
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  input uart_0__tx__o;
  OB uart_0__tx_0 (
    .I(uart_0__tx__o),
    .O(uart_0__tx__io)
  );
endmodule

(* \amaranth.hierarchy  = "top.tb" *)
(* generator = "Amaranth" *)
module tb(ui__tb_fanin_flags__in_start, ui__tb_fanin_flags__in_done, ui__tb_fanout_flags__trigger, ui__done, ui__inactive, ui__load, rst, clk);
  reg \$auto$verilog_backend.cc:2083:dump_module$2  = 0;
  (* src = "amaram/common/Delayer.py:258" *)
  wire \$1 ;
  (* src = "amaram/common/Delayer.py:259" *)
  wire \$3 ;
  (* src = "amaram/common/Delayer.py:192" *)
  reg _ui__done = 1'h0;
  (* src = "amaram/common/Delayer.py:192" *)
  reg \_ui__done$next ;
  (* src = "amaram/common/Delayer.py:192" *)
  reg _ui__inactive = 1'h0;
  (* src = "amaram/common/Delayer.py:192" *)
  reg \_ui__inactive$next ;
  (* src = "amaram/common/Delayer.py:192" *)
  reg [11:0] _ui__load = 12'h000;
  (* src = "amaram/common/Delayer.py:192" *)
  reg [11:0] \_ui__load$next ;
  (* src = "amaram/common/Delayer.py:192" *)
  reg _ui__tb_fanin_flags__in_done = 1'h0;
  (* src = "amaram/common/Delayer.py:192" *)
  reg \_ui__tb_fanin_flags__in_done$next ;
  (* src = "amaram/common/Delayer.py:192" *)
  reg _ui__tb_fanin_flags__in_start = 1'h0;
  (* src = "amaram/common/Delayer.py:192" *)
  reg \_ui__tb_fanin_flags__in_start$next ;
  (* src = "amaram/common/Delayer.py:192" *)
  reg _ui__tb_fanout_flags__trigger = 1'h0;
  (* src = "amaram/common/Delayer.py:192" *)
  reg \_ui__tb_fanout_flags__trigger$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input clk;
  (* src = "amaram/common/Delayer.py:108" *)
  reg [1:0] delay_fsm_state = 2'h0;
  (* src = "amaram/common/Delayer.py:108" *)
  reg [1:0] \delay_fsm_state$next ;
  (* src = "amaram/common/Delayer.py:79" *)
  wire delayer_ui__done;
  (* src = "amaram/common/Delayer.py:79" *)
  wire delayer_ui__inactive;
  (* src = "amaram/common/Delayer.py:79" *)
  reg [11:0] delayer_ui__load = 12'h000;
  (* src = "amaram/common/Delayer.py:79" *)
  reg [11:0] \delayer_ui__load$next ;
  (* src = "amaram/common/Delayer.py:255" *)
  reg [1:0] fsm_state = 2'h2;
  (* src = "amaram/common/Delayer.py:255" *)
  reg [1:0] \fsm_state$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  input rst;
  (* src = "amaram/common/Delayer.py:183" *)
  output ui__done;
  reg ui__done = 1'h0;
  (* src = "amaram/common/Delayer.py:183" *)
  reg \ui__done$next ;
  (* src = "amaram/common/Delayer.py:183" *)
  output ui__inactive;
  reg ui__inactive = 1'h0;
  (* src = "amaram/common/Delayer.py:183" *)
  reg \ui__inactive$next ;
  (* src = "amaram/common/Delayer.py:183" *)
  input [11:0] ui__load;
  (* src = "amaram/common/Delayer.py:183" *)
  output ui__tb_fanin_flags__in_done;
  reg ui__tb_fanin_flags__in_done = 1'h0;
  (* src = "amaram/common/Delayer.py:183" *)
  reg \ui__tb_fanin_flags__in_done$next ;
  (* src = "amaram/common/Delayer.py:183" *)
  output ui__tb_fanin_flags__in_start;
  reg ui__tb_fanin_flags__in_start = 1'h0;
  (* src = "amaram/common/Delayer.py:183" *)
  reg \ui__tb_fanin_flags__in_start$next ;
  (* src = "amaram/common/Delayer.py:183" *)
  input ui__tb_fanout_flags__trigger;
  always @(posedge clk)
    _ui__load <= \_ui__load$next ;
  always @(posedge clk)
    _ui__done <= \_ui__done$next ;
  always @(posedge clk)
    _ui__inactive <= \_ui__inactive$next ;
  always @(posedge clk)
    delayer_ui__load <= \delayer_ui__load$next ;
  always @(posedge clk)
    _ui__tb_fanin_flags__in_start <= \_ui__tb_fanin_flags__in_start$next ;
  always @(posedge clk)
    _ui__tb_fanin_flags__in_done <= \_ui__tb_fanin_flags__in_done$next ;
  always @(posedge clk)
    fsm_state <= \fsm_state$next ;
  always @(posedge clk)
    delay_fsm_state <= \delay_fsm_state$next ;
  assign \$1  = ! (* src = "amaram/common/Delayer.py:258" *) fsm_state;
  assign \$3  = fsm_state == (* src = "amaram/common/Delayer.py:259" *) 1'h1;
  always @(posedge clk)
    ui__tb_fanin_flags__in_start <= \ui__tb_fanin_flags__in_start$next ;
  always @(posedge clk)
    ui__tb_fanin_flags__in_done <= \ui__tb_fanin_flags__in_done$next ;
  always @(posedge clk)
    _ui__tb_fanout_flags__trigger <= \_ui__tb_fanout_flags__trigger$next ;
  always @(posedge clk)
    ui__done <= \ui__done$next ;
  always @(posedge clk)
    ui__inactive <= \ui__inactive$next ;
  delayer delayer (
    .clk(clk),
    .rst(rst),
    .ui__done(delayer_ui__done),
    .ui__inactive(delayer_ui__inactive),
    .ui__load(delayer_ui__load)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \ui__tb_fanin_flags__in_start$next  = _ui__tb_fanin_flags__in_start;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__tb_fanin_flags__in_start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \ui__tb_fanin_flags__in_done$next  = _ui__tb_fanin_flags__in_done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__tb_fanin_flags__in_done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \_ui__tb_fanin_flags__in_done$next  = \$3 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__tb_fanin_flags__in_done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \fsm_state$next  = fsm_state;
    (* src = "amaram/common/Delayer.py:255" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "INITIAL/2" */
      /* src = "amaram/common/Delayer.py:262" */
      2'h2:
          (* src = "amaram/common/Delayer.py:263" *)
          casez (_ui__tb_fanout_flags__trigger)
            /* src = "amaram/common/Delayer.py:263" */
            1'h1:
                \fsm_state$next  = 2'h0;
          endcase
      /* \amaranth.decoding  = "START/0" */
      /* src = "amaram/common/Delayer.py:266" */
      2'h0:
          (* src = "amaram/common/Delayer.py:267" *)
          casez (_ui__done)
            /* src = "amaram/common/Delayer.py:267" */
            1'h1:
                \fsm_state$next  = 2'h1;
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \fsm_state$next  = 2'h2;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \delay_fsm_state$next  = delay_fsm_state;
    (* src = "amaram/common/Delayer.py:255" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "INITIAL/2" */
      /* src = "amaram/common/Delayer.py:262" */
      2'h2:
          /* empty */;
      /* \amaranth.decoding  = "START/0" */
      /* src = "amaram/common/Delayer.py:266" */
      2'h0:
          (* src = "amaram/common/Delayer.py:108" *)
          casez (delay_fsm_state)
            /* \amaranth.decoding  = "INIT/0" */
            /* src = "amaram/common/Delayer.py:109" */
            2'h0:
                \delay_fsm_state$next  = 2'h1;
            /* \amaranth.decoding  = "LOADED/1" */
            /* src = "amaram/common/Delayer.py:112" */
            2'h1:
                \delay_fsm_state$next  = 2'h2;
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \delay_fsm_state$next  = 2'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \_ui__tb_fanout_flags__trigger$next  = ui__tb_fanout_flags__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__tb_fanout_flags__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \ui__done$next  = _ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \ui__inactive$next  = _ui__inactive;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__inactive$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \_ui__load$next  = ui__load;
    (* src = "amaram/common/Delayer.py:255" *)
    casez (fsm_state)
      /* \amaranth.decoding  = "INITIAL/2" */
      /* src = "amaram/common/Delayer.py:262" */
      2'h2:
          /* empty */;
      /* \amaranth.decoding  = "START/0" */
      /* src = "amaram/common/Delayer.py:266" */
      2'h0:
          (* src = "amaram/common/Delayer.py:108" *)
          casez (delay_fsm_state)
            /* \amaranth.decoding  = "INIT/0" */
            /* src = "amaram/common/Delayer.py:109" */
            2'h0:
                \_ui__load$next  = 12'h958;
            /* \amaranth.decoding  = "LOADED/1" */
            /* src = "amaram/common/Delayer.py:112" */
            2'h1:
                \_ui__load$next  = 12'h000;
          endcase
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__load$next  = 12'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \_ui__done$next  = delayer_ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \_ui__inactive$next  = delayer_ui__inactive;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__inactive$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \delayer_ui__load$next  = _ui__load;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \delayer_ui__load$next  = 12'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$2 ) begin end
    \_ui__tb_fanin_flags__in_start$next  = \$1 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \_ui__tb_fanin_flags__in_start$next  = 1'h0;
    endcase
  end
endmodule

(* \amaranth.hierarchy  = "top" *)
(* top =  1  *)
(* generator = "Amaranth" *)
module top(led_0__io, led_1__io, led_2__io, led_3__io, led_4__io, led_5__io, led_6__io, led_7__io, esp32_spi_0__en__io, esp32_spi_0__tx__io, esp32_spi_0__rx__io, esp32_spi_0__gpio4_copi__io, esp32_spi_0__gpio5_cs__io, esp32_spi_0__gpio12_cipo__io, esp32_spi_0__gpio16_sclk__io, uart_0__rx__io, uart_0__tx__io, uart_0__rts__io, uart_0__dtr__io, clk25_0__io, button_pwr_0__io
, button_fire_0__io, button_fire_1__io, button_up_0__io, button_down_0__io, button_left_0__io, button_right_0__io, esp32_spi_0__gpio0__io);
  reg \$auto$verilog_backend.cc:2083:dump_module$3  = 0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire [4:0] \$1 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *)
  wire \$10 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *)
  wire \$11 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$14 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$16 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$18 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire [4:0] \$2 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$20 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$22 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *)
  wire \$24 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$26 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$28 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *)
  wire \$30 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$32 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$34 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *)
  wire \$36 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:114" *)
  wire \$38 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire [4:0] \$4 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:114" *)
  wire \$40 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:117" *)
  wire \$42 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:117" *)
  wire \$44 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:120" *)
  wire \$46 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:120" *)
  wire \$48 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *)
  wire \$5 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:123" *)
  wire \$50 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:123" *)
  wire \$52 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$54 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$56 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
  wire \$58 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$60 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$62 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *)
  wire \$64 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$66 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$68 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *)
  wire \$70 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$72 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *)
  wire \$74 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *)
  wire \$76 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$78 ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *)
  wire \$8 ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *)
  wire \$80 ;
  (* src = "amaram/common/Delayer.py:397" *)
  wire [7:0] \$82 ;
  (* \amaranth.sample_reg  = 32'd1 *)
  (* src = "amaram/common/Delayer.py:388" *)
  reg \$sample$s$start$sync$1  = 1'h0;
  (* src = "amaram/common/Delayer.py:388" *)
  wire \$sample$s$start$sync$1$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_down_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_fire_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_left_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_pwr_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_right_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input button_up_0__io;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  wire clk;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input clk25_0__io;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:30" *)
  reg [3:0] clk_counter = 4'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:30" *)
  reg [3:0] \clk_counter$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__en__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  inout esp32_spi_0__gpio0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__gpio12_cipo__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio16_sclk__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio4_copi__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__gpio5_cs__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input esp32_spi_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output esp32_spi_0__tx__io;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_button_ffsync_i_buttons__left;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_button_ffsync_i_buttons__pwr;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:85" *)
  wire i_button_ffsync_i_buttons__right;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__down = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__down$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__fireA = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__fireA$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__fireB = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__fireB$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__left = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__left$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__pwr = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__pwr$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__right = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__right$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg i_button_ffsync_i_unsync_buttons__up = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:61" *)
  reg \i_button_ffsync_i_unsync_buttons__up$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_0__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_1__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_2__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_3__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_4__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_5__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_6__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output led_7__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_down_0_button_down_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_fire_0_button_fire_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_fire_1_button_fire_1__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_left_0_button_left_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_pwr_0_button_pwr_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_right_0_button_right_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_button_up_0_button_up_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_clk25_0_clk25_0__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__en_esp32_spi_0__en__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__en_esp32_spi_0__en__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_esp32_spi_0__tx_esp32_spi_0__tx__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_0_led_0__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_1_led_1__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_2_led_2__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_3_led_3__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_4_led_4__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_5_led_5__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_6_led_6__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_led_7_led_7__o;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__dtr_uart_0__dtr__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rts_uart_0__rts__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  wire pin_uart_0__rx_uart_0__rx__i;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg pin_uart_0__tx_uart_0__tx__o = 1'h0;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:143" *)
  reg \pin_uart_0__tx_uart_0__tx__o$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  reg rst = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:40" *)
  reg \rst$next ;
  (* src = "amaram/common/Delayer.py:388" *)
  reg start = 1'h0;
  (* src = "amaram/common/Delayer.py:388" *)
  reg \start$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  reg sync_1e6_clk = 1'h0;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  reg \sync_1e6_clk$next ;
  (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:26" *)
  wire sync_1e6_rst;
  (* src = "amaram/common/Delayer.py:183" *)
  wire tb_ui__done;
  (* src = "amaram/common/Delayer.py:183" *)
  wire tb_ui__inactive;
  (* src = "amaram/common/Delayer.py:183" *)
  reg [11:0] tb_ui__load = 12'h000;
  (* src = "amaram/common/Delayer.py:183" *)
  reg [11:0] \tb_ui__load$next ;
  (* src = "amaram/common/Delayer.py:183" *)
  wire tb_ui__tb_fanin_flags__in_done;
  (* src = "amaram/common/Delayer.py:183" *)
  wire tb_ui__tb_fanin_flags__in_start;
  (* src = "amaram/common/Delayer.py:183" *)
  reg tb_ui__tb_fanout_flags__trigger = 1'h0;
  (* src = "amaram/common/Delayer.py:183" *)
  reg \tb_ui__tb_fanout_flags__trigger$next ;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__dtr__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rts__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  input uart_0__rx__io;
  (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/build/res.py:129" *)
  output uart_0__tx__io;
  (* src = "amaram/common/Delayer.py:381" *)
  reg ui__done = 1'h0;
  (* src = "amaram/common/Delayer.py:381" *)
  reg \ui__done$next ;
  (* src = "amaram/common/Delayer.py:381" *)
  reg ui__inactive = 1'h0;
  (* src = "amaram/common/Delayer.py:381" *)
  reg \ui__inactive$next ;
  (* src = "amaram/common/Delayer.py:381" *)
  wire [11:0] ui__load;
  (* src = "amaram/common/Delayer.py:381" *)
  reg ui__tb_fanin_flags__in_done = 1'h0;
  (* src = "amaram/common/Delayer.py:381" *)
  reg \ui__tb_fanin_flags__in_done$next ;
  (* src = "amaram/common/Delayer.py:381" *)
  reg ui__tb_fanin_flags__in_start = 1'h0;
  (* src = "amaram/common/Delayer.py:381" *)
  reg \ui__tb_fanin_flags__in_start$next ;
  (* src = "amaram/common/Delayer.py:381" *)
  reg ui__tb_fanout_flags__trigger = 1'h0;
  (* src = "amaram/common/Delayer.py:381" *)
  reg \ui__tb_fanout_flags__trigger$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__pwr <= \i_button_ffsync_i_unsync_buttons__pwr$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__fireA <= \i_button_ffsync_i_unsync_buttons__fireA$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__fireB <= \i_button_ffsync_i_unsync_buttons__fireB$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__up <= \i_button_ffsync_i_unsync_buttons__up$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__down <= \i_button_ffsync_i_unsync_buttons__down$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__left <= \i_button_ffsync_i_unsync_buttons__left$next ;
  always @(posedge sync_1e6_clk)
    i_button_ffsync_i_unsync_buttons__right <= \i_button_ffsync_i_unsync_buttons__right$next ;
  assign \$11  = ! (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *) clk_counter;
  assign \$10  = \$11  ? (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *) \$8  : sync_1e6_clk;
  assign \$18  = \$14  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *) \$16 ;
  assign \$20  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$22  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$24  = \$20  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *) \$22 ;
  assign \$28  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$2  = clk_counter + (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *) 1'h1;
  assign \$30  = \$26  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *) \$28 ;
  assign \$32  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$36  = \$32  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *) \$34 ;
  assign \$38  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:114" *) i_button_ffsync_i_buttons__pwr;
  assign \$42  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:117" *) i_button_ffsync_i_buttons__pwr;
  assign \$46  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:120" *) i_button_ffsync_i_buttons__pwr;
  assign \$50  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:123" *) i_button_ffsync_i_buttons__pwr;
  assign \$58  = \$54  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *) \$56 ;
  assign \$5  = clk_counter == (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *) 4'hb;
  assign \$60  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$62  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$64  = \$60  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" *) \$62 ;
  assign \$68  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__rts_uart_0__rts__i;
  assign \$4  = \$5  ? (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:32" *) 5'h00 : \$2 ;
  assign \$70  = \$66  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" *) \$68 ;
  assign \$72  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/rec.py:258" *) pin_uart_0__dtr_uart_0__dtr__i;
  assign \$76  = \$72  & (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" *) \$74 ;
  assign \$78  = ~ (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) \$sample$s$start$sync$1 ;
  assign \$80  = \$78  & (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/ast.py:1369" *) start;
  assign \$82  = + (* src = "amaram/common/Delayer.py:397" *) { i_button_ffsync_i_buttons__left, i_button_ffsync_i_buttons__right, ui__tb_fanin_flags__in_done, ui__tb_fanin_flags__in_start };
  always @(posedge clk)
    \$sample$s$start$sync$1  <= \$sample$s$start$sync$1$next ;
  always @(posedge clk)
    clk_counter <= \clk_counter$next ;
  always @(posedge clk)
    sync_1e6_clk <= \sync_1e6_clk$next ;
  always @(posedge clk)
    pin_esp32_spi_0__tx_esp32_spi_0__tx__o <= \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next ;
  always @(posedge clk)
    pin_uart_0__tx_uart_0__tx__o <= \pin_uart_0__tx_uart_0__tx__o$next ;
  always @(posedge clk)
    pin_esp32_spi_0__en_esp32_spi_0__en__o <= \pin_esp32_spi_0__en_esp32_spi_0__en__o$next ;
  assign \$8  = ~ (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/clks.py:33" *) sync_1e6_clk;
  always @(posedge clk)
    pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o <= \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next ;
  always @(posedge clk)
    ui__tb_fanin_flags__in_start <= \ui__tb_fanin_flags__in_start$next ;
  always @(posedge clk)
    ui__tb_fanin_flags__in_done <= \ui__tb_fanin_flags__in_done$next ;
  always @(posedge clk)
    tb_ui__tb_fanout_flags__trigger <= \tb_ui__tb_fanout_flags__trigger$next ;
  always @(posedge clk)
    ui__done <= \ui__done$next ;
  always @(posedge clk)
    ui__inactive <= \ui__inactive$next ;
  always @(posedge clk)
    tb_ui__load <= \tb_ui__load$next ;
  always @(posedge clk)
    start <= \start$next ;
  always @(posedge clk)
    ui__tb_fanout_flags__trigger <= \ui__tb_fanout_flags__trigger$next ;
  always @(posedge clk)
    rst <= \rst$next ;
  i_button_ffsync i_button_ffsync (
    .clk(clk),
    .i_buttons__left(i_button_ffsync_i_buttons__left),
    .i_buttons__pwr(i_button_ffsync_i_buttons__pwr),
    .i_buttons__right(i_button_ffsync_i_buttons__right),
    .i_unsync_buttons__down(i_button_ffsync_i_unsync_buttons__down),
    .i_unsync_buttons__fireA(i_button_ffsync_i_unsync_buttons__fireA),
    .i_unsync_buttons__fireB(i_button_ffsync_i_unsync_buttons__fireB),
    .i_unsync_buttons__left(i_button_ffsync_i_unsync_buttons__left),
    .i_unsync_buttons__pwr(i_button_ffsync_i_unsync_buttons__pwr),
    .i_unsync_buttons__right(i_button_ffsync_i_unsync_buttons__right),
    .i_unsync_buttons__up(i_button_ffsync_i_unsync_buttons__up),
    .rst(rst)
  );
  pin_button_down_0 pin_button_down_0 (
    .button_down_0__i(pin_button_down_0_button_down_0__i),
    .button_down_0__io(button_down_0__io)
  );
  pin_button_fire_0 pin_button_fire_0 (
    .button_fire_0__i(pin_button_fire_0_button_fire_0__i),
    .button_fire_0__io(button_fire_0__io)
  );
  pin_button_fire_1 pin_button_fire_1 (
    .button_fire_1__i(pin_button_fire_1_button_fire_1__i),
    .button_fire_1__io(button_fire_1__io)
  );
  pin_button_left_0 pin_button_left_0 (
    .button_left_0__i(pin_button_left_0_button_left_0__i),
    .button_left_0__io(button_left_0__io)
  );
  pin_button_pwr_0 pin_button_pwr_0 (
    .button_pwr_0__i(pin_button_pwr_0_button_pwr_0__i),
    .button_pwr_0__io(button_pwr_0__io)
  );
  pin_button_right_0 pin_button_right_0 (
    .button_right_0__i(pin_button_right_0_button_right_0__i),
    .button_right_0__io(button_right_0__io)
  );
  pin_button_up_0 pin_button_up_0 (
    .button_up_0__i(pin_button_up_0_button_up_0__i),
    .button_up_0__io(button_up_0__io)
  );
  pin_clk25_0 pin_clk25_0 (
    .clk25_0__i(pin_clk25_0_clk25_0__i),
    .clk25_0__io(clk25_0__io)
  );
  pin_esp32_spi_0__en pin_esp32_spi_0__en (
    .esp32_spi_0__en__io(esp32_spi_0__en__io),
    .esp32_spi_0__en__o(pin_esp32_spi_0__en_esp32_spi_0__en__o)
  );
  pin_esp32_spi_0__gpio0 pin_esp32_spi_0__gpio0 (
    .esp32_spi_0__gpio0__io(esp32_spi_0__gpio0__io),
    .esp32_spi_0__gpio0__o(pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o)
  );
  pin_esp32_spi_0__gpio12_cipo pin_esp32_spi_0__gpio12_cipo (
    .esp32_spi_0__gpio12_cipo__io(esp32_spi_0__gpio12_cipo__io)
  );
  pin_esp32_spi_0__gpio16_sclk pin_esp32_spi_0__gpio16_sclk (
    .esp32_spi_0__gpio16_sclk__io(esp32_spi_0__gpio16_sclk__io)
  );
  pin_esp32_spi_0__gpio4_copi pin_esp32_spi_0__gpio4_copi (
    .esp32_spi_0__gpio4_copi__io(esp32_spi_0__gpio4_copi__io)
  );
  pin_esp32_spi_0__gpio5_cs pin_esp32_spi_0__gpio5_cs (
    .esp32_spi_0__gpio5_cs__io(esp32_spi_0__gpio5_cs__io)
  );
  pin_esp32_spi_0__rx pin_esp32_spi_0__rx (
    .esp32_spi_0__rx__i(pin_esp32_spi_0__rx_esp32_spi_0__rx__i),
    .esp32_spi_0__rx__io(esp32_spi_0__rx__io)
  );
  pin_esp32_spi_0__tx pin_esp32_spi_0__tx (
    .esp32_spi_0__tx__io(esp32_spi_0__tx__io),
    .esp32_spi_0__tx__o(pin_esp32_spi_0__tx_esp32_spi_0__tx__o)
  );
  pin_led_0 pin_led_0 (
    .led_0__io(led_0__io),
    .led_0__o(pin_led_0_led_0__o)
  );
  pin_led_1 pin_led_1 (
    .led_1__io(led_1__io),
    .led_1__o(pin_led_1_led_1__o)
  );
  pin_led_2 pin_led_2 (
    .led_2__io(led_2__io),
    .led_2__o(pin_led_2_led_2__o)
  );
  pin_led_3 pin_led_3 (
    .led_3__io(led_3__io),
    .led_3__o(pin_led_3_led_3__o)
  );
  pin_led_4 pin_led_4 (
    .led_4__io(led_4__io),
    .led_4__o(pin_led_4_led_4__o)
  );
  pin_led_5 pin_led_5 (
    .led_5__io(led_5__io),
    .led_5__o(pin_led_5_led_5__o)
  );
  pin_led_6 pin_led_6 (
    .led_6__io(led_6__io),
    .led_6__o(pin_led_6_led_6__o)
  );
  pin_led_7 pin_led_7 (
    .led_7__io(led_7__io),
    .led_7__o(pin_led_7_led_7__o)
  );
  pin_uart_0__dtr pin_uart_0__dtr (
    .uart_0__dtr__i(pin_uart_0__dtr_uart_0__dtr__i),
    .uart_0__dtr__io(uart_0__dtr__io)
  );
  pin_uart_0__rts pin_uart_0__rts (
    .uart_0__rts__i(pin_uart_0__rts_uart_0__rts__i),
    .uart_0__rts__io(uart_0__rts__io)
  );
  pin_uart_0__rx pin_uart_0__rx (
    .uart_0__rx__i(pin_uart_0__rx_uart_0__rx__i),
    .uart_0__rx__io(uart_0__rx__io)
  );
  pin_uart_0__tx pin_uart_0__tx (
    .uart_0__tx__io(uart_0__tx__io),
    .uart_0__tx__o(pin_uart_0__tx_uart_0__tx__o)
  );
  tb tb (
    .clk(clk),
    .rst(rst),
    .ui__done(tb_ui__done),
    .ui__inactive(tb_ui__inactive),
    .ui__load(tb_ui__load),
    .ui__tb_fanin_flags__in_done(tb_ui__tb_fanin_flags__in_done),
    .ui__tb_fanin_flags__in_start(tb_ui__tb_fanin_flags__in_start),
    .ui__tb_fanout_flags__trigger(tb_ui__tb_fanout_flags__trigger)
  );
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \clk_counter$next  = \$4 [3:0];
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \clk_counter$next  = 4'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next  = pin_uart_0__rx_uart_0__rx__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__tx_esp32_spi_0__tx__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pin_uart_0__tx_uart_0__tx__o$next  = pin_esp32_spi_0__rx_esp32_spi_0__rx__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_uart_0__tx_uart_0__tx__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = pin_esp32_spi_0__en_esp32_spi_0__en__o;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
    casez ({ \$36 , \$30 , \$24 , \$18  })
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" */
      4'b???1:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$40 ;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" */
      4'b??1?:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$44 ;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" */
      4'b?1??:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$48 ;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" */
      4'b1???:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = \$52 ;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__en_esp32_spi_0__en__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o;
    (* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" *)
    casez ({ \$76 , \$70 , \$64 , \$58  })
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:113" */
      4'b???1:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:116" */
      4'b??1?:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:119" */
      4'b?1??:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h1;
      /* src = "/home/ubuntu/from_host/x/Documents/git_repos/gateware/amtest/amtest/boards/ulx3s/common/upload.py:122" */
      4'b1???:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h0;
    endcase
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \pin_esp32_spi_0__gpio0_esp32_spi_0__gpio0__o$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \ui__tb_fanin_flags__in_start$next  = tb_ui__tb_fanin_flags__in_start;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__tb_fanin_flags__in_start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \ui__tb_fanin_flags__in_done$next  = tb_ui__tb_fanin_flags__in_done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__tb_fanin_flags__in_done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \tb_ui__tb_fanout_flags__trigger$next  = ui__tb_fanout_flags__trigger;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \tb_ui__tb_fanout_flags__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \ui__done$next  = tb_ui__done;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__done$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \ui__inactive$next  = tb_ui__inactive;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__inactive$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \tb_ui__load$next  = 12'h000;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \tb_ui__load$next  = 12'h000;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \sync_1e6_clk$next  = \$10 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \sync_1e6_clk$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \start$next  = i_button_ffsync_i_buttons__left;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \start$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \ui__tb_fanout_flags__trigger$next  = \$80 ;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \ui__tb_fanout_flags__trigger$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \rst$next  = i_button_ffsync_i_buttons__right;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (rst)
      1'h1:
          \rst$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__pwr$next  = pin_button_pwr_0_button_pwr_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__pwr$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__fireA$next  = pin_button_fire_0_button_fire_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__fireA$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__fireB$next  = pin_button_fire_1_button_fire_1__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__fireB$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__up$next  = pin_button_up_0_button_up_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__up$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__down$next  = pin_button_down_0_button_down_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__down$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__left$next  = pin_button_left_0_button_left_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__left$next  = 1'h0;
    endcase
  end
  always @* begin
    if (\$auto$verilog_backend.cc:2083:dump_module$3 ) begin end
    \i_button_ffsync_i_unsync_buttons__right$next  = pin_button_right_0_button_right_0__i;
    (* src = "/home/ubuntu/Documents/venv_fpga/lib/python3.8/site-packages/amaranth/hdl/xfrm.py:519" *)
    casez (sync_1e6_rst)
      1'h1:
          \i_button_ffsync_i_unsync_buttons__right$next  = 1'h0;
    endcase
  end
  assign \$1  = \$4 ;
  assign sync_1e6_rst = 1'h0;
  assign ui__load = 12'h000;
  assign \$sample$s$start$sync$1$next  = start;
  assign { pin_led_7_led_7__o, pin_led_6_led_6__o, pin_led_5_led_5__o, pin_led_4_led_4__o, pin_led_3_led_3__o, pin_led_2_led_2__o, pin_led_1_led_1__o, pin_led_0_led_0__o } = \$82 ;
  assign clk = pin_clk25_0_clk25_0__i;
  assign \$14  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$16  = pin_uart_0__rts_uart_0__rts__i;
  assign \$26  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$34  = pin_uart_0__rts_uart_0__rts__i;
  assign \$40  = \$38 ;
  assign \$44  = \$42 ;
  assign \$48  = 1'h0;
  assign \$52  = \$50 ;
  assign \$54  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$56  = pin_uart_0__rts_uart_0__rts__i;
  assign \$66  = pin_uart_0__dtr_uart_0__dtr__i;
  assign \$74  = pin_uart_0__rts_uart_0__rts__i;
endmodule
